###
#
# RU Makefile
#
###

all:	slib

slib:
	cd plog; make slib;
	cd com; make slib;
	cd string; make slib;
	cd log; make slib;
	cd cmd; make slib;


clean:
	cd plog; make clean;
	cd com; make clean;
	cd string; make clean;
	cd log; make clean;
	cd cmd; make clean;


