
#ifndef _H_u_o_ran_operations
#define _H_u_o_ran_operations
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2019, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 18.10-15

    User SIL-SA header
    bundle o-ran_all
    module o-ran-operations
    revision 2019-02-04
    namespace urn:o-ran:operations:1.0
    organization O-RAN Alliance
    Created: 2019-12-20T02:20:30Z
    CLI parameters:
        defnames true
        format uh
        indent 4
        module ietf-yang-types
        module ietf-inet-types
        module ietf-interfaces
        module iana-if-type
        module ietf-ip
        module iana-hardware
        module ietf-hardware
        module ietf-netconf-acm
        module o-ran-hardware
        module o-ran-software-management
        module o-ran-interfaces
        module o-ran-transceiver
        module o-ran-mplane-int
        module o-ran-dhcp
        module o-ran-compression-factors
        module o-ran-uplane-conf
        module o-ran-module-cap
        module o-ran-processing-element
        module o-ran-performance-management
        module o-ran-fm
        module o-ran-lbm
        module o-ran-supervision
        module o-ran-beamforming
        module o-ran-operations
        module o-ran-usermgmt
        module o-ran-sync
        sil-bundle o-ran_all
        sil-get2
        sil-sa
        unified true

 */

#include <xmlstring.h>

#include "agt.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "dlq.h"
#include "ncxtypes.h"
#include "op.h"
#include "rpc.h"
#include "ses.h"
#include "status.h"
#include "val.h"
#include "y_o-ran-operations.h"
#include "u_ietf-yang-types.h"
#include "u_ietf-inet-types.h"
#include "u_ietf-interfaces.h"
#include "u_iana-if-type.h"
#include "u_ietf-ip.h"
#include "u_iana-hardware.h"
#include "u_ietf-hardware.h"
#include "u_ietf-netconf-acm.h"
#include "u_o-ran-hardware.h"
#include "u_o-ran-software-management.h"
#include "u_o-ran-interfaces.h"
#include "u_o-ran-transceiver.h"
#include "u_o-ran-mplane-int.h"
#include "u_o-ran-dhcp.h"
#include "u_o-ran-compression-factors.h"
#include "u_o-ran-uplane-conf.h"
#include "u_o-ran-module-cap.h"
#include "u_o-ran-processing-element.h"
#include "u_o-ran-performance-management.h"
#include "u_o-ran-fm.h"
#include "u_o-ran-lbm.h"
#include "u_o-ran-supervision.h"
#include "u_o-ran-beamforming.h"
#include "u_o-ran-usermgmt.h"
#include "u_o-ran-sync.h"

#ifdef __cplusplus
extern "C" {
#endif

/* list /operational-info/declarations/supported-header-mechanism */
typedef struct y_o_ran_operations_T_operational_info_declarations_supported_header_mechanism_ {
    dlq_hdr_t qhdr;
    xmlChar *v_protocol;
    boolean v_ecpri_concatenation_support;
    xmlChar *v_protocol_version;
} y_o_ran_operations_T_operational_info_declarations_supported_header_mechanism;

/* container /operational-info/declarations */
typedef struct y_o_ran_operations_T_operational_info_declarations_ {
    xmlChar *v_supported_mplane_version;
    xmlChar *v_supported_cusplane_version;
    dlq_hdr_t v_supported_header_mechanism;
} y_o_ran_operations_T_operational_info_declarations;

/* container /operational-info/operational-state */
typedef struct y_o_ran_operations_T_operational_info_operational_state_ {
    xmlChar *v_restart_cause;
    xmlChar *v_restart_datetime;
} y_o_ran_operations_T_operational_info_operational_state;

/* container /operational-info/clock */
typedef struct y_o_ran_operations_T_operational_info_clock_ {
    int16 v_timezone_utc_offset;
} y_o_ran_operations_T_operational_info_clock;

/* container /operational-info */
typedef struct y_o_ran_operations_T_operational_info_ {
    y_o_ran_operations_T_operational_info_declarations v_declarations;
    y_o_ran_operations_T_operational_info_operational_state v_operational_state;
    y_o_ran_operations_T_operational_info_clock v_clock;
    uint16 v_re_call_home_no_ssh_timer;
} y_o_ran_operations_T_operational_info;

/* container /reset/input */
typedef struct y_o_ran_operations_T_reset_input_ {
} y_o_ran_operations_T_reset_input;

/* container /reset/output */
typedef struct y_o_ran_operations_T_reset_output_ {
} y_o_ran_operations_T_reset_output;

/* rpc /reset */
typedef struct y_o_ran_operations_T_reset_ {
    y_o_ran_operations_T_reset_input v_input;
    y_o_ran_operations_T_reset_output v_output;
} y_o_ran_operations_T_reset;

/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_declarations_supported_header_mechanism_get
*
* Get database object callback for list supported-header-mechanism
* Path: /operational-info/declarations/supported-header-mechanism
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_declarations_supported_header_mechanism_get (
    getcb_get2_t *get2cb,
    const xmlChar *k_operational_info_declarations_supported_header_mechanism_protocol,
    boolean protocol_fixed,
    boolean protocol_present);

/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_declarations_get
*
* Get database object callback for container declarations
* Path: /operational-info/declarations
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_declarations_get (
    getcb_get2_t *get2cb);

/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_operational_state_get
*
* Get database object callback for container operational-state
* Path: /operational-info/operational-state
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_operational_state_get (
    getcb_get2_t *get2cb);


/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_clock_timezone_utc_offset_edit
*
* Edit database object callback
* Path: /operational-info/clock/timezone-utc-offset
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_clock_timezone_utc_offset_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval);


/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_clock_edit
*
* Edit database object callback
* Path: /operational-info/clock
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_clock_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval);


/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_re_call_home_no_ssh_timer_edit
*
* Edit database object callback
* Path: /operational-info/re-call-home-no-ssh-timer
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_re_call_home_no_ssh_timer_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval);


/********************************************************************
* FUNCTION u_o_ran_operations_operational_info_edit
*
* Edit database object callback
* Path: /operational-info
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_operational_info_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval);


/********************************************************************
* FUNCTION u_o_ran_operations_reset_validate
*
* RPC validation phase
* All YANG constraints have passed at this point.
* Add description-stmt checks in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_reset_validate (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode);


/********************************************************************
* FUNCTION u_o_ran_operations_reset_invoke
*
* RPC invocation phase
* All constraints have passed at this point.
* Call device instrumentation code in this function.
*
* INPUTS:
*     see agt/agt_rpc.h for details
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_reset_invoke (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    xml_node_t *methnode);

/********************************************************************
* FUNCTION u_o_ran_operations_init
*
* initialize the o-ran-operations server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_init (
    const xmlChar *modname,
    const xmlChar *revision);

/********************************************************************
* FUNCTION u_o_ran_operations_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
extern status_t u_o_ran_operations_init2 (void);

/********************************************************************
* FUNCTION u_o_ran_operations_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
extern void u_o_ran_operations_cleanup (void);

#ifdef __cplusplus
} /* end extern 'C' */
#endif

#endif
