
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2019, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 18.10-15

    YumaPro SIL-SA module
    bundle o-ran_all
    module ietf-hardware
    revision 2018-03-13
    namespace urn:ietf:params:xml:ns:yang:ietf-hardware
    organization IETF NETMOD (Network Modeling) Working Group
    Created: 2019-12-20T02:20:31Z
    CLI parameters:
        defnames true
        format yc
        indent 4
        module ietf-yang-types
        module ietf-inet-types
        module ietf-interfaces
        module iana-if-type
        module ietf-ip
        module iana-hardware
        module ietf-hardware
        module ietf-netconf-acm
        module o-ran-hardware
        module o-ran-software-management
        module o-ran-interfaces
        module o-ran-transceiver
        module o-ran-mplane-int
        module o-ran-dhcp
        module o-ran-compression-factors
        module o-ran-uplane-conf
        module o-ran-module-cap
        module o-ran-processing-element
        module o-ran-performance-management
        module o-ran-fm
        module o-ran-lbm
        module o-ran-supervision
        module o-ran-beamforming
        module o-ran-operations
        module o-ran-usermgmt
        module o-ran-sync
        sil-bundle o-ran_all
        sil-get2
        sil-sa
        unified true

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_not.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "ses.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_util.h"
#include "xml_val.h"

/* SIL bundle: o-ran_all */
#include "y_ietf-yang-types.h"
#include "u_ietf-yang-types.h"
#include "y_ietf-inet-types.h"
#include "u_ietf-inet-types.h"
#include "y_ietf-interfaces.h"
#include "u_ietf-interfaces.h"
#include "y_iana-if-type.h"
#include "u_iana-if-type.h"
#include "y_ietf-ip.h"
#include "u_ietf-ip.h"
#include "y_iana-hardware.h"
#include "u_iana-hardware.h"
#include "y_ietf-hardware.h"
#include "u_ietf-hardware.h"
#include "y_ietf-netconf-acm.h"
#include "u_ietf-netconf-acm.h"
#include "y_o-ran-hardware.h"
#include "u_o-ran-hardware.h"
#include "y_o-ran-software-management.h"
#include "u_o-ran-software-management.h"
#include "y_o-ran-interfaces.h"
#include "u_o-ran-interfaces.h"
#include "y_o-ran-transceiver.h"
#include "u_o-ran-transceiver.h"
#include "y_o-ran-mplane-int.h"
#include "u_o-ran-mplane-int.h"
#include "y_o-ran-dhcp.h"
#include "u_o-ran-dhcp.h"
#include "y_o-ran-compression-factors.h"
#include "u_o-ran-compression-factors.h"
#include "y_o-ran-uplane-conf.h"
#include "u_o-ran-uplane-conf.h"
#include "y_o-ran-module-cap.h"
#include "u_o-ran-module-cap.h"
#include "y_o-ran-processing-element.h"
#include "u_o-ran-processing-element.h"
#include "y_o-ran-performance-management.h"
#include "u_o-ran-performance-management.h"
#include "y_o-ran-fm.h"
#include "u_o-ran-fm.h"
#include "y_o-ran-lbm.h"
#include "u_o-ran-lbm.h"
#include "y_o-ran-supervision.h"
#include "u_o-ran-supervision.h"
#include "y_o-ran-beamforming.h"
#include "u_o-ran-beamforming.h"
#include "y_o-ran-operations.h"
#include "u_o-ran-operations.h"
#include "y_o-ran-usermgmt.h"
#include "u_o-ran-usermgmt.h"
#include "y_o-ran-sync.h"
#include "u_o-ran-sync.h"

/* module static variables */
static ncx_module_t *ietf_hardware_mod;
static obj_template_t *hardware_obj;
static val_value_t *hardware_val;

/********************************************************************
* FUNCTION y_ietf_hardware_init_static_vars
*
* initialize module static variables
*
********************************************************************/
static void y_ietf_hardware_init_static_vars (void)
{
    ietf_hardware_mod = NULL;
    hardware_obj = NULL;
    hardware_val = NULL;

} /* y_ietf_hardware_init_static_vars */

/********************************************************************
* FUNCTION ietf_hardware_hardware_last_change_get
*
* Get database object callback for leaf last-change
* Path: /hardware/last-change
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_last_change_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    return u_ietf_hardware_hardware_last_change_get(get2cb);

} /* ietf_hardware_hardware_last_change_get */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_class_edit
*
* Edit database object callback
* Path: /hardware/component/class
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_class_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_class_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_class_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_class_edit */


#ifdef u_ietf_hardware_F_entity_mib
/********************************************************************
* FUNCTION ietf_hardware_hardware_component_physical_index_get
*
* Get database object callback for leaf physical-index
* Path: /hardware/component/physical-index
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_physical_index_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_physical_index_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_physical_index_get */

#endif /* u_ietf_hardware_F_entity_mib */
/********************************************************************
* FUNCTION ietf_hardware_hardware_component_description_get
*
* Get database object callback for leaf description
* Path: /hardware/component/description
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_description_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_description_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_description_get */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_parent_edit
*
* Edit database object callback
* Path: /hardware/component/parent
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_parent_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_parent_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_parent_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_parent_edit */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_parent_rel_pos_edit
*
* Edit database object callback
* Path: /hardware/component/parent-rel-pos
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_parent_rel_pos_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_parent_rel_pos_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_parent_rel_pos_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_parent_rel_pos_edit */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_contains_child_get
*
* Get database object callback for leaf-list contains-child
* Path: /hardware/component/contains-child
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_contains_child_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_contains_child_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_contains_child_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_hardware_rev_get
*
* Get database object callback for leaf hardware-rev
* Path: /hardware/component/hardware-rev
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_hardware_rev_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_hardware_rev_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_hardware_rev_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_firmware_rev_get
*
* Get database object callback for leaf firmware-rev
* Path: /hardware/component/firmware-rev
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_firmware_rev_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_firmware_rev_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_firmware_rev_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_software_rev_get
*
* Get database object callback for leaf software-rev
* Path: /hardware/component/software-rev
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_software_rev_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_software_rev_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_software_rev_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_serial_num_get
*
* Get database object callback for leaf serial-num
* Path: /hardware/component/serial-num
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_serial_num_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_serial_num_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_serial_num_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_mfg_name_get
*
* Get database object callback for leaf mfg-name
* Path: /hardware/component/mfg-name
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_mfg_name_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_mfg_name_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_mfg_name_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_model_name_get
*
* Get database object callback for leaf model-name
* Path: /hardware/component/model-name
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_model_name_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_model_name_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_model_name_get */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_alias_edit
*
* Edit database object callback
* Path: /hardware/component/alias
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_alias_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_alias_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_alias_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_alias_edit */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_asset_id_edit
*
* Edit database object callback
* Path: /hardware/component/asset-id
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_asset_id_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_asset_id_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_asset_id_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_asset_id_edit */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_is_fru_get
*
* Get database object callback for leaf is-fru
* Path: /hardware/component/is-fru
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_is_fru_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_is_fru_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_is_fru_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_mfg_date_get
*
* Get database object callback for leaf mfg-date
* Path: /hardware/component/mfg-date
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_mfg_date_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_mfg_date_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_mfg_date_get */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_uri_edit
*
* Edit database object callback
* Path: /hardware/component/uri
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_uri_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_uri_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_uri_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_uri_edit */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_uuid_get
*
* Get database object callback for leaf uuid
* Path: /hardware/component/uuid
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_uuid_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_uuid_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_uuid_get */


#ifdef u_ietf_hardware_F_hardware_state
/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_state_last_changed_get
*
* Get database object callback for leaf state-last-changed
* Path: /hardware/component/state/state-last-changed
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_state_last_changed_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_state_state_last_changed_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_state_state_last_changed_get */


/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_admin_state_edit
*
* Edit database object callback
* Path: /hardware/component/state/admin-state
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_admin_state_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_state_admin_state_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_state_admin_state_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_state_admin_state_edit */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_oper_state_get
*
* Get database object callback for leaf oper-state
* Path: /hardware/component/state/oper-state
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_oper_state_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_state_oper_state_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_state_oper_state_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_usage_state_get
*
* Get database object callback for leaf usage-state
* Path: /hardware/component/state/usage-state
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_usage_state_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_state_usage_state_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_state_usage_state_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_alarm_state_get
*
* Get database object callback for leaf alarm-state
* Path: /hardware/component/state/alarm-state
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_alarm_state_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_state_alarm_state_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_state_alarm_state_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_standby_state_get
*
* Get database object callback for leaf standby-state
* Path: /hardware/component/state/standby-state
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_standby_state_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_state_standby_state_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_state_standby_state_get */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_state_edit
*
* Edit database object callback
* Path: /hardware/component/state
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_state_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_state_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_state_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_state_edit */
#endif /* u_ietf_hardware_F_hardware_state */

#ifdef u_ietf_hardware_F_hardware_sensor
/********************************************************************
* FUNCTION ietf_hardware_hardware_component_sensor_data_get
*
* Get database object callback for container sensor-data
* Path: /hardware/component/sensor-data
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_sensor_data_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-hardware:name */
    const xmlChar *k_hardware_component_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_N_name);
    if (keyval) {
        k_hardware_component_name = VAL_STRING(keyval);
    }

    return u_ietf_hardware_hardware_component_sensor_data_get(
        get2cb,
        k_hardware_component_name);

} /* ietf_hardware_hardware_component_sensor_data_get */

#endif /* u_ietf_hardware_F_hardware_sensor */

/********************************************************************
* FUNCTION ietf_hardware_hardware_component_edit
*
* Edit database object callback
* Path: /hardware/component
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_component_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* local key ietf-hardware:name */
    const xmlChar *k_hardware_component_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_component_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_component_edit(scb, msg, cbtyp, editop, newval, curval,
        k_hardware_component_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_component_edit */


/********************************************************************
* FUNCTION ietf_hardware_hardware_edit
*
* Edit database object callback
* Path: /hardware
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_hardware_hardware_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_hardware_hardware_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_hardware_hardware_edit(scb, msg, cbtyp, editop, newval, curval);

    if (res == NO_ERR && cbtyp == AGT_CB_COMMIT) {
        res = agt_check_cache(&hardware_val, newval, curval, editop);
    }
    

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_hardware_hardware_edit */

/********************************************************************
* FUNCTION y_ietf_hardware_init
*
* initialize the ietf-hardware server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t y_ietf_hardware_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    y_ietf_hardware_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_ietf_hardware_M_ietf_hardware)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_ietf_hardware_R_ietf_hardware)) {
        return ERR_NCX_WRONG_VERSION;
    }

    res = ncx_set_feature_enable(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"entity-mib",
#ifdef u_ietf_hardware_F_entity_mib
        true);
#else
        false);
#endif
    if (res != NO_ERR) {
        return res;
    }

    res = ncx_set_feature_enable(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"hardware-state",
#ifdef u_ietf_hardware_F_hardware_state
        true);
#else
        false);
#endif
    if (res != NO_ERR) {
        return res;
    }

    res = ncx_set_feature_enable(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"hardware-sensor",
#ifdef u_ietf_hardware_F_hardware_sensor
        true);
#else
        false);
#endif
    if (res != NO_ERR) {
        return res;
    }



    res = ncxmod_load_module(
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_R_ietf_hardware,
        agt_get_savedevQ(),
        &ietf_hardware_mod);
    if (res != NO_ERR) {
        return res;
    }

    hardware_obj = ncx_find_object(
        ietf_hardware_mod,
        y_ietf_hardware_N_hardware);
    if (hardware_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:last-change",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_last_change_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:class",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_class_edit);
    if (res != NO_ERR) {
        return res;
    }


#ifdef u_ietf_hardware_F_entity_mib
    if (ncx_feature_enabled_str(
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_R_ietf_hardware,
        (const xmlChar *)"entity-mib")) {
        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:physical-index",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_physical_index_get);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_hardware_F_entity_mib */
#endif /* u_ietf_hardware_F_entity_mib */

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:description",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_description_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:parent",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_parent_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:parent-rel-pos",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_parent_rel_pos_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:contains-child",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_contains_child_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:hardware-rev",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_hardware_rev_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:firmware-rev",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_firmware_rev_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:software-rev",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_software_rev_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:serial-num",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_serial_num_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:mfg-name",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_mfg_name_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:model-name",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_model_name_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:alias",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_alias_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:asset-id",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_asset_id_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:is-fru",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_is_fru_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:mfg-date",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_mfg_date_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:uri",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_uri_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component/hw:uuid",
        y_ietf_hardware_R_ietf_hardware,
        ietf_hardware_hardware_component_uuid_get);
    if (res != NO_ERR) {
        return res;
    }


#ifdef u_ietf_hardware_F_hardware_state
    if (ncx_feature_enabled_str(
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_R_ietf_hardware,
        (const xmlChar *)"hardware-state")) {
        res = agt_cb_register_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_edit);
        if (res != NO_ERR) {
            return res;
        }

        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state/hw:state-last-changed",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_state_last_changed_get);
        if (res != NO_ERR) {
            return res;
        }

        res = agt_cb_register_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state/hw:admin-state",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_admin_state_edit);
        if (res != NO_ERR) {
            return res;
        }

        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state/hw:oper-state",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_oper_state_get);
        if (res != NO_ERR) {
            return res;
        }

        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state/hw:usage-state",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_usage_state_get);
        if (res != NO_ERR) {
            return res;
        }

        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state/hw:alarm-state",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_alarm_state_get);
        if (res != NO_ERR) {
            return res;
        }

        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state/hw:standby-state",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_state_standby_state_get);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_hardware_F_hardware_state */
#endif /* u_ietf_hardware_F_hardware_state */


#ifdef u_ietf_hardware_F_hardware_sensor
    if (ncx_feature_enabled_str(
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_R_ietf_hardware,
        (const xmlChar *)"hardware-sensor")) {
        res = agt_cb_register_get_callback(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:sensor-data",
            y_ietf_hardware_R_ietf_hardware,
            ietf_hardware_hardware_component_sensor_data_get);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_hardware_F_hardware_sensor */
#endif /* u_ietf_hardware_F_hardware_sensor */

    res = u_ietf_hardware_init(modname, revision);
    return res;

} /* y_ietf_hardware_init */

/********************************************************************
* FUNCTION y_ietf_hardware_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t y_ietf_hardware_init2 (void)
{
    status_t res = NO_ERR;

    res = u_ietf_hardware_init2();

    return res;

} /* y_ietf_hardware_init2 */

/********************************************************************
* FUNCTION y_ietf_hardware_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void y_ietf_hardware_cleanup (void)
{

    agt_cb_unregister_callbacks(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware");

    agt_cb_unregister_callbacks(
        y_ietf_hardware_M_ietf_hardware,
        (const xmlChar *)"/hw:hardware/hw:component");


#ifdef u_ietf_hardware_F_hardware_state
    if (ncx_feature_enabled_str(
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_R_ietf_hardware,
        (const xmlChar *)"hardware-state")) {
        agt_cb_unregister_callbacks(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:state");
    } /* u_ietf_hardware_F_hardware_state */
#endif /* u_ietf_hardware_F_hardware_state */


#ifdef u_ietf_hardware_F_hardware_sensor
    if (ncx_feature_enabled_str(
        y_ietf_hardware_M_ietf_hardware,
        y_ietf_hardware_R_ietf_hardware,
        (const xmlChar *)"hardware-sensor")) {
        agt_cb_unregister_callbacks(
            y_ietf_hardware_M_ietf_hardware,
            (const xmlChar *)"/hw:hardware/hw:component/hw:sensor-data");
    } /* u_ietf_hardware_F_hardware_sensor */
#endif /* u_ietf_hardware_F_hardware_sensor */

    u_ietf_hardware_cleanup();

} /* y_ietf_hardware_cleanup */

/* END SIL-SA y_ietf_hardware.c */
