
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2019, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 18.10-15

    YumaPro SIL-SA module
    bundle o-ran_all
    module ietf-ip
    revision 2018-02-22
    namespace urn:ietf:params:xml:ns:yang:ietf-ip
    organization IETF NETMOD (Network Modeling) Working Group
    Created: 2019-12-20T02:20:31Z
    CLI parameters:
        defnames true
        format yc
        indent 4
        module ietf-yang-types
        module ietf-inet-types
        module ietf-interfaces
        module iana-if-type
        module ietf-ip
        module iana-hardware
        module ietf-hardware
        module ietf-netconf-acm
        module o-ran-hardware
        module o-ran-software-management
        module o-ran-interfaces
        module o-ran-transceiver
        module o-ran-mplane-int
        module o-ran-dhcp
        module o-ran-compression-factors
        module o-ran-uplane-conf
        module o-ran-module-cap
        module o-ran-processing-element
        module o-ran-performance-management
        module o-ran-fm
        module o-ran-lbm
        module o-ran-supervision
        module o-ran-beamforming
        module o-ran-operations
        module o-ran-usermgmt
        module o-ran-sync
        sil-bundle o-ran_all
        sil-get2
        sil-sa
        unified true

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_val.h"

/* SIL bundle: o-ran_all */
#include "y_ietf-yang-types.h"
#include "u_ietf-yang-types.h"
#include "y_ietf-inet-types.h"
#include "u_ietf-inet-types.h"
#include "y_ietf-interfaces.h"
#include "u_ietf-interfaces.h"
#include "y_iana-if-type.h"
#include "u_iana-if-type.h"
#include "y_ietf-ip.h"
#include "u_ietf-ip.h"
#include "y_iana-hardware.h"
#include "u_iana-hardware.h"
#include "y_ietf-hardware.h"
#include "u_ietf-hardware.h"
#include "y_ietf-netconf-acm.h"
#include "u_ietf-netconf-acm.h"
#include "y_o-ran-hardware.h"
#include "u_o-ran-hardware.h"
#include "y_o-ran-software-management.h"
#include "u_o-ran-software-management.h"
#include "y_o-ran-interfaces.h"
#include "u_o-ran-interfaces.h"
#include "y_o-ran-transceiver.h"
#include "u_o-ran-transceiver.h"
#include "y_o-ran-mplane-int.h"
#include "u_o-ran-mplane-int.h"
#include "y_o-ran-dhcp.h"
#include "u_o-ran-dhcp.h"
#include "y_o-ran-compression-factors.h"
#include "u_o-ran-compression-factors.h"
#include "y_o-ran-uplane-conf.h"
#include "u_o-ran-uplane-conf.h"
#include "y_o-ran-module-cap.h"
#include "u_o-ran-module-cap.h"
#include "y_o-ran-processing-element.h"
#include "u_o-ran-processing-element.h"
#include "y_o-ran-performance-management.h"
#include "u_o-ran-performance-management.h"
#include "y_o-ran-fm.h"
#include "u_o-ran-fm.h"
#include "y_o-ran-lbm.h"
#include "u_o-ran-lbm.h"
#include "y_o-ran-supervision.h"
#include "u_o-ran-supervision.h"
#include "y_o-ran-beamforming.h"
#include "u_o-ran-beamforming.h"
#include "y_o-ran-operations.h"
#include "u_o-ran-operations.h"
#include "y_o-ran-usermgmt.h"
#include "u_o-ran-usermgmt.h"
#include "y_o-ran-sync.h"
#include "u_o-ran-sync.h"

/* module static variables */
static ncx_module_t *ietf_ip_mod;

/********************************************************************
* FUNCTION y_ietf_ip_init_static_vars
*
* initialize module static variables
*
********************************************************************/
static void y_ietf_ip_init_static_vars (void)
{
    ietf_ip_mod = NULL;

} /* y_ietf_ip_init_static_vars */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_enabled_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/enabled
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_enabled_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_enabled_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_enabled_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_enabled_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_forwarding_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/forwarding
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_forwarding_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_forwarding_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_forwarding_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_forwarding_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_mtu_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/mtu
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_mtu_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_mtu_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_mtu_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_mtu_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_address_subnet_prefix_length_prefix_length_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/address/subnet/prefix-length/prefix-length
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_address_subnet_prefix_length_prefix_length_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_address_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_address_subnet_prefix_length_prefix_length_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_address_subnet_prefix_length_prefix_length_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_address_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_address_subnet_prefix_length_prefix_length_edit */


#ifdef u_ietf_ip_F_ipv4_non_contiguous_netmasks
/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_address_subnet_netmask_netmask_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/address/subnet/netmask/netmask
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_address_subnet_netmask_netmask_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_address_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_address_subnet_netmask_netmask_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_address_subnet_netmask_netmask_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_address_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_address_subnet_netmask_netmask_edit */
#endif /* u_ietf_ip_F_ipv4_non_contiguous_netmasks */
/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_address_origin_get
*
* Get database object callback for leaf origin
* Path: /interfaces/interface/ipv4/address/origin
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_address_origin_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_address_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv4_address_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv4_address_origin_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_address_ip);

} /* ietf_ip_interfaces_interface_ipv4_address_origin_get */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_address_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/address
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_address_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_address_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_address_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_address_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_address_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_address_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_neighbor_link_layer_address_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/neighbor/link-layer-address
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_neighbor_link_layer_address_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_neighbor_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_neighbor_link_layer_address_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_neighbor_link_layer_address_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_neighbor_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_neighbor_link_layer_address_edit */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_neighbor_origin_get
*
* Get database object callback for leaf origin
* Path: /interfaces/interface/ipv4/neighbor/origin
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_neighbor_origin_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_neighbor_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv4_neighbor_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv4_neighbor_origin_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_neighbor_ip);

} /* ietf_ip_interfaces_interface_ipv4_neighbor_origin_get */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_neighbor_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4/neighbor
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_neighbor_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv4_neighbor_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_neighbor_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_neighbor_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv4_neighbor_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_neighbor_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv4_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv4
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv4_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv4_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv4_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv4_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_enabled_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/enabled
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_enabled_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_enabled_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_enabled_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_enabled_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_forwarding_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/forwarding
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_forwarding_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_forwarding_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_forwarding_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_forwarding_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_mtu_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/mtu
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_mtu_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_mtu_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_mtu_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_mtu_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_address_prefix_length_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/address/prefix-length
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_address_prefix_length_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_address_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_address_prefix_length_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_address_prefix_length_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_address_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_address_prefix_length_edit */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_address_origin_get
*
* Get database object callback for leaf origin
* Path: /interfaces/interface/ipv6/address/origin
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_address_origin_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_address_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv6_address_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv6_address_origin_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_address_ip);

} /* ietf_ip_interfaces_interface_ipv6_address_origin_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_address_status_get
*
* Get database object callback for leaf status
* Path: /interfaces/interface/ipv6/address/status
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_address_status_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_address_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv6_address_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv6_address_status_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_address_ip);

} /* ietf_ip_interfaces_interface_ipv6_address_status_get */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_address_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/address
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_address_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_address_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_address_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_address_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_address_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_address_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_neighbor_link_layer_address_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/neighbor/link-layer-address
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_neighbor_link_layer_address_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_neighbor_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_neighbor_link_layer_address_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_neighbor_link_layer_address_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_neighbor_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_neighbor_link_layer_address_edit */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_neighbor_origin_get
*
* Get database object callback for leaf origin
* Path: /interfaces/interface/ipv6/neighbor/origin
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_neighbor_origin_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_neighbor_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv6_neighbor_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv6_neighbor_origin_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_neighbor_ip);

} /* ietf_ip_interfaces_interface_ipv6_neighbor_origin_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_neighbor_is_router_get
*
* Get database object callback for leaf is-router
* Path: /interfaces/interface/ipv6/neighbor/is-router
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_neighbor_is_router_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_neighbor_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv6_neighbor_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv6_neighbor_is_router_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_neighbor_ip);

} /* ietf_ip_interfaces_interface_ipv6_neighbor_is_router_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_neighbor_state_get
*
* Get database object callback for leaf state
* Path: /interfaces/interface/ipv6/neighbor/state
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_neighbor_state_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_neighbor_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_interface_ipv6_neighbor_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_interface_ipv6_neighbor_state_get(
        get2cb,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_neighbor_ip);

} /* ietf_ip_interfaces_interface_ipv6_neighbor_state_get */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_neighbor_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/neighbor
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_neighbor_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_interface_ipv6_neighbor_ip =
        VAL_STRING(sil_sa_get_key(msg, 2));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_neighbor_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_neighbor_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name,
        k_interfaces_interface_ipv6_neighbor_ip);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_neighbor_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_dup_addr_detect_transmits_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/dup-addr-detect-transmits
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_dup_addr_detect_transmits_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_dup_addr_detect_transmits_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_dup_addr_detect_transmits_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_dup_addr_detect_transmits_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_autoconf_create_global_addresses_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/autoconf/create-global-addresses
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_autoconf_create_global_addresses_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_autoconf_create_global_addresses_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_autoconf_create_global_addresses_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_autoconf_create_global_addresses_edit */


#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_autoconf_create_temporary_addresses_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/autoconf/create-temporary-addresses
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_autoconf_create_temporary_addresses_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_autoconf_create_temporary_addresses_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_autoconf_create_temporary_addresses_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_autoconf_create_temporary_addresses_edit */
#endif /* u_ietf_ip_F_ipv6_privacy_autoconf */

#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_autoconf_temporary_valid_lifetime_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/autoconf/temporary-valid-lifetime
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_autoconf_temporary_valid_lifetime_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_autoconf_temporary_valid_lifetime_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_autoconf_temporary_valid_lifetime_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_autoconf_temporary_valid_lifetime_edit */
#endif /* u_ietf_ip_F_ipv6_privacy_autoconf */

#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_autoconf_temporary_preferred_lifetime_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/autoconf/temporary-preferred-lifetime
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_autoconf_temporary_preferred_lifetime_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_autoconf_temporary_preferred_lifetime_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_autoconf_temporary_preferred_lifetime_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_autoconf_temporary_preferred_lifetime_edit */
#endif /* u_ietf_ip_F_ipv6_privacy_autoconf */

/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_autoconf_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6/autoconf
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_autoconf_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_autoconf_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_autoconf_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_autoconf_edit */


/********************************************************************
* FUNCTION ietf_ip_interfaces_interface_ipv6_edit
*
* Edit database object callback
* Path: /interfaces/interface/ipv6
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_interface_ipv6_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_interface_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter ietf_ip_interfaces_interface_ipv6_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_ietf_ip_interfaces_interface_ipv6_edit(scb, msg, cbtyp, editop, newval, curval,
        k_interfaces_interface_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* ietf_ip_interfaces_interface_ipv6_edit */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv4_address_subnet_get
*
* Get database object callback for choice subnet
* Path: /interfaces-state/interface/ipv4/address/subnet
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv4_address_subnet_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    /* ancestor key ietf-ip:ip */
    const xmlChar *k_interfaces_state_interface_ipv4_address_ip = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_state_interface_ipv4_address_ip = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_state_interface_ipv4_address_subnet_get(
        get2cb,
        k_interfaces_state_interface_name,
        k_interfaces_state_interface_ipv4_address_ip);

} /* ietf_ip_interfaces_state_interface_ipv4_address_subnet_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv4_address_get
*
* Get database object callback for list address
* Path: /interfaces-state/interface/ipv4/address
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv4_address_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_state_interface_ipv4_address_ip = 0;
    boolean ip_fixed = FALSE;
    boolean ip_present = FALSE;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_state_interface_ipv4_address_ip = VAL_STRING(keyval);
        ip_fixed = VAL_IS_FIXED_VALUE(keyval);
        ip_present = TRUE;
    }

    return u_ietf_ip_interfaces_state_interface_ipv4_address_get(
        get2cb,
        k_interfaces_state_interface_name,
        k_interfaces_state_interface_ipv4_address_ip,
        ip_fixed,
        ip_present);

} /* ietf_ip_interfaces_state_interface_ipv4_address_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv4_neighbor_get
*
* Get database object callback for list neighbor
* Path: /interfaces-state/interface/ipv4/neighbor
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv4_neighbor_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_state_interface_ipv4_neighbor_ip = 0;
    boolean ip_fixed = FALSE;
    boolean ip_present = FALSE;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_state_interface_ipv4_neighbor_ip = VAL_STRING(keyval);
        ip_fixed = VAL_IS_FIXED_VALUE(keyval);
        ip_present = TRUE;
    }

    return u_ietf_ip_interfaces_state_interface_ipv4_neighbor_get(
        get2cb,
        k_interfaces_state_interface_name,
        k_interfaces_state_interface_ipv4_neighbor_ip,
        ip_fixed,
        ip_present);

} /* ietf_ip_interfaces_state_interface_ipv4_neighbor_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv4_get
*
* Get database object callback for container ipv4
* Path: /interfaces-state/interface/ipv4
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv4_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_state_interface_ipv4_get(
        get2cb,
        k_interfaces_state_interface_name);

} /* ietf_ip_interfaces_state_interface_ipv4_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv6_address_get
*
* Get database object callback for list address
* Path: /interfaces-state/interface/ipv6/address
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv6_address_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_state_interface_ipv6_address_ip = 0;
    boolean ip_fixed = FALSE;
    boolean ip_present = FALSE;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_state_interface_ipv6_address_ip = VAL_STRING(keyval);
        ip_fixed = VAL_IS_FIXED_VALUE(keyval);
        ip_present = TRUE;
    }

    return u_ietf_ip_interfaces_state_interface_ipv6_address_get(
        get2cb,
        k_interfaces_state_interface_name,
        k_interfaces_state_interface_ipv6_address_ip,
        ip_fixed,
        ip_present);

} /* ietf_ip_interfaces_state_interface_ipv6_address_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv6_neighbor_get
*
* Get database object callback for list neighbor
* Path: /interfaces-state/interface/ipv6/neighbor
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv6_neighbor_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    /* local key ietf-ip:ip */
    const xmlChar *k_interfaces_state_interface_ipv6_neighbor_ip = 0;
    boolean ip_fixed = FALSE;
    boolean ip_present = FALSE;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_N_ip);
    if (keyval) {
        k_interfaces_state_interface_ipv6_neighbor_ip = VAL_STRING(keyval);
        ip_fixed = VAL_IS_FIXED_VALUE(keyval);
        ip_present = TRUE;
    }

    return u_ietf_ip_interfaces_state_interface_ipv6_neighbor_get(
        get2cb,
        k_interfaces_state_interface_name,
        k_interfaces_state_interface_ipv6_neighbor_ip,
        ip_fixed,
        ip_present);

} /* ietf_ip_interfaces_state_interface_ipv6_neighbor_get */

/********************************************************************
* FUNCTION ietf_ip_interfaces_state_interface_ipv6_get
*
* Get database object callback for container ipv6
* Path: /interfaces-state/interface/ipv6
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t ietf_ip_interfaces_state_interface_ipv6_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* ancestor key ietf-interfaces:name */
    const xmlChar *k_interfaces_state_interface_name = 0;
    keyval = getcb_find_key_str(get2cb,
        y_ietf_interfaces_M_ietf_interfaces,
        y_ietf_interfaces_N_name);
    if (keyval) {
        k_interfaces_state_interface_name = VAL_STRING(keyval);
    }

    return u_ietf_ip_interfaces_state_interface_ipv6_get(
        get2cb,
        k_interfaces_state_interface_name);

} /* ietf_ip_interfaces_state_interface_ipv6_get */

/********************************************************************
* FUNCTION y_ietf_ip_init
*
* initialize the ietf-ip server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t y_ietf_ip_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    y_ietf_ip_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_ietf_ip_M_ietf_ip)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_ietf_ip_R_ietf_ip)) {
        return ERR_NCX_WRONG_VERSION;
    }

    res = ncx_set_feature_enable(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"ipv4-non-contiguous-netmasks",
#ifdef u_ietf_ip_F_ipv4_non_contiguous_netmasks
        true);
#else
        false);
#endif
    if (res != NO_ERR) {
        return res;
    }

    res = ncx_set_feature_enable(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"ipv6-privacy-autoconf",
#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
        true);
#else
        false);
#endif
    if (res != NO_ERR) {
        return res;
    }



    res = ncxmod_load_module(
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_R_ietf_ip,
        agt_get_savedevQ(),
        &ietf_ip_mod);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:enabled",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_enabled_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:forwarding",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_forwarding_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:mtu",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_mtu_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:address",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_address_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:address/ip:subnet/ip:prefix-length/ip:prefix-length",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_address_subnet_prefix_length_prefix_length_edit);
    if (res != NO_ERR) {
        return res;
    }


#ifdef u_ietf_ip_F_ipv4_non_contiguous_netmasks
    if (ncx_feature_enabled_str(
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_R_ietf_ip,
        (const xmlChar *)"ipv4-non-contiguous-netmasks")) {
        res = agt_cb_register_callback(
            y_ietf_ip_M_ietf_ip,
            (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:address/ip:subnet/ip:netmask/ip:netmask",
            y_ietf_ip_R_ietf_ip,
            ietf_ip_interfaces_interface_ipv4_address_subnet_netmask_netmask_edit);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_ip_F_ipv4_non_contiguous_netmasks */
#endif /* u_ietf_ip_F_ipv4_non_contiguous_netmasks */

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:address/ip:origin",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_address_origin_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:neighbor",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_neighbor_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:neighbor/ip:link-layer-address",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_neighbor_link_layer_address_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:neighbor/ip:origin",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv4_neighbor_origin_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:enabled",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_enabled_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:forwarding",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_forwarding_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:mtu",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_mtu_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:address",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_address_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:address/ip:prefix-length",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_address_prefix_length_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:address/ip:origin",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_address_origin_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:address/ip:status",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_address_status_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:neighbor",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_neighbor_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:neighbor/ip:link-layer-address",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_neighbor_link_layer_address_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:neighbor/ip:origin",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_neighbor_origin_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:neighbor/ip:is-router",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_neighbor_is_router_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:neighbor/ip:state",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_neighbor_state_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:dup-addr-detect-transmits",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_dup_addr_detect_transmits_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:autoconf",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_autoconf_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:autoconf/ip:create-global-addresses",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_interface_ipv6_autoconf_create_global_addresses_edit);
    if (res != NO_ERR) {
        return res;
    }


#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
    if (ncx_feature_enabled_str(
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_R_ietf_ip,
        (const xmlChar *)"ipv6-privacy-autoconf")) {
        res = agt_cb_register_callback(
            y_ietf_ip_M_ietf_ip,
            (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:autoconf/ip:create-temporary-addresses",
            y_ietf_ip_R_ietf_ip,
            ietf_ip_interfaces_interface_ipv6_autoconf_create_temporary_addresses_edit);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_ip_F_ipv6_privacy_autoconf */
#endif /* u_ietf_ip_F_ipv6_privacy_autoconf */


#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
    if (ncx_feature_enabled_str(
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_R_ietf_ip,
        (const xmlChar *)"ipv6-privacy-autoconf")) {
        res = agt_cb_register_callback(
            y_ietf_ip_M_ietf_ip,
            (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:autoconf/ip:temporary-valid-lifetime",
            y_ietf_ip_R_ietf_ip,
            ietf_ip_interfaces_interface_ipv6_autoconf_temporary_valid_lifetime_edit);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_ip_F_ipv6_privacy_autoconf */
#endif /* u_ietf_ip_F_ipv6_privacy_autoconf */


#ifdef u_ietf_ip_F_ipv6_privacy_autoconf
    if (ncx_feature_enabled_str(
        y_ietf_ip_M_ietf_ip,
        y_ietf_ip_R_ietf_ip,
        (const xmlChar *)"ipv6-privacy-autoconf")) {
        res = agt_cb_register_callback(
            y_ietf_ip_M_ietf_ip,
            (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:autoconf/ip:temporary-preferred-lifetime",
            y_ietf_ip_R_ietf_ip,
            ietf_ip_interfaces_interface_ipv6_autoconf_temporary_preferred_lifetime_edit);
        if (res != NO_ERR) {
            return res;
        }
    } /* u_ietf_ip_F_ipv6_privacy_autoconf */
#endif /* u_ietf_ip_F_ipv6_privacy_autoconf */

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv4_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4/ip:address",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv4_address_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4/ip:address/ip:subnet",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv4_address_subnet_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4/ip:neighbor",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv4_neighbor_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv6",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv6_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv6/ip:address",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv6_address_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv6/ip:neighbor",
        y_ietf_ip_R_ietf_ip,
        ietf_ip_interfaces_state_interface_ipv6_neighbor_get);
    if (res != NO_ERR) {
        return res;
    }

    res = u_ietf_ip_init(modname, revision);
    return res;

} /* y_ietf_ip_init */

/********************************************************************
* FUNCTION y_ietf_ip_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t y_ietf_ip_init2 (void)
{
    status_t res = NO_ERR;

    res = u_ietf_ip_init2();

    return res;

} /* y_ietf_ip_init2 */

/********************************************************************
* FUNCTION y_ietf_ip_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void y_ietf_ip_cleanup (void)
{

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:address");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv4/ip:neighbor");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:address");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:neighbor");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces/if:interface/ip:ipv6/ip:autoconf");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4/ip:address");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4/ip:address/ip:subnet");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv4/ip:neighbor");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv6");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv6/ip:address");

    agt_cb_unregister_callbacks(
        y_ietf_ip_M_ietf_ip,
        (const xmlChar *)"/if:interfaces-state/if:interface/ip:ipv6/ip:neighbor");

    u_ietf_ip_cleanup();

} /* y_ietf_ip_cleanup */

/* END SIL-SA y_ietf_ip.c */
