
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2019, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 18.10-15

    YumaPro SIL-SA module
    module o-ran-troubleshooting
    revision 2019-02-04
    namespace urn:o-ran:troubleshooting:1.0
    organization O-RAN Alliance
    Created: 2019-12-20T02:20:28Z
    CLI parameters:
        format yc
        indent 4
        module o-ran-troubleshooting
        output y_o-ran-troubleshooting.c
        sil-get2
        sil-sa
        unified true

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_not.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "ses.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_util.h"
#include "xml_val.h"
#include "u_o-ran-troubleshooting.h"
#include "y_o-ran-troubleshooting.h"

/* module static variables */
static ncx_module_t *o_ran_troubleshooting_mod;
static obj_template_t *start_troubleshooting_logs_obj;
static obj_template_t *stop_troubleshooting_logs_obj;

/********************************************************************
* FUNCTION y_o_ran_troubleshooting_init_static_vars
*
* initialize module static variables
*
********************************************************************/
static void y_o_ran_troubleshooting_init_static_vars (void)
{
    o_ran_troubleshooting_mod = NULL;
    start_troubleshooting_logs_obj = NULL;
    stop_troubleshooting_logs_obj = NULL;

} /* y_o_ran_troubleshooting_init_static_vars */

/********************************************************************
* FUNCTION y_o_ran_troubleshooting_init
*
* initialize the o-ran-troubleshooting server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t y_o_ran_troubleshooting_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    y_o_ran_troubleshooting_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_o_ran_troubleshooting_M_o_ran_troubleshooting)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_o_ran_troubleshooting_R_o_ran_troubleshooting)) {
        return ERR_NCX_WRONG_VERSION;
    }


    res = ncxmod_load_module(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_R_o_ran_troubleshooting,
        agt_get_savedevQ(),
        &o_ran_troubleshooting_mod);
    if (res != NO_ERR) {
        return res;
    }

    start_troubleshooting_logs_obj = ncx_find_object(
        o_ran_troubleshooting_mod,
        y_o_ran_troubleshooting_N_start_troubleshooting_logs);
    if (start_troubleshooting_logs_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    stop_troubleshooting_logs_obj = ncx_find_object(
        o_ran_troubleshooting_mod,
        y_o_ran_troubleshooting_N_stop_troubleshooting_logs);
    if (stop_troubleshooting_logs_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    res = agt_rpc_register_method(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_N_start_troubleshooting_logs,
        AGT_RPC_PH_VALIDATE,
        u_o_ran_troubleshooting_start_troubleshooting_logs_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_N_start_troubleshooting_logs,
        AGT_RPC_PH_INVOKE,
        u_o_ran_troubleshooting_start_troubleshooting_logs_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_N_stop_troubleshooting_logs,
        AGT_RPC_PH_VALIDATE,
        u_o_ran_troubleshooting_stop_troubleshooting_logs_validate);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_rpc_register_method(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_N_stop_troubleshooting_logs,
        AGT_RPC_PH_INVOKE,
        u_o_ran_troubleshooting_stop_troubleshooting_logs_invoke);
    if (res != NO_ERR) {
        return res;
    }

    res = u_o_ran_troubleshooting_init(modname, revision);
    return res;

} /* y_o_ran_troubleshooting_init */

/********************************************************************
* FUNCTION y_o_ran_troubleshooting_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t y_o_ran_troubleshooting_init2 (void)
{
    status_t res = NO_ERR;

    res = u_o_ran_troubleshooting_init2();

    return res;

} /* y_o_ran_troubleshooting_init2 */

/********************************************************************
* FUNCTION y_o_ran_troubleshooting_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void y_o_ran_troubleshooting_cleanup (void)
{

    agt_rpc_unregister_method(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_N_start_troubleshooting_logs);

    agt_rpc_unregister_method(
        y_o_ran_troubleshooting_M_o_ran_troubleshooting,
        y_o_ran_troubleshooting_N_stop_troubleshooting_logs);
    u_o_ran_troubleshooting_cleanup();

} /* y_o_ran_troubleshooting_cleanup */

/* END SIL-SA y_o_ran_troubleshooting.c */
