/*!
 * @skip  $ld:$
 * @file  f_du_reg_jsfb.h
 * @brief レジスタアドレス定義ヘッダ(JSFB)
 * @date  2018/08/15 FJT) Yoshida
 *
 * All Rights Reserved, Copyright (C) FUJITSU LIMITED 2018
 */

/*!
 * @addtogroup RRH_RRH
 * @{
 */
#ifndef F_DU_REG_JSFB_H
#define F_DU_REG_JSFB_H

/*!
 * @name JSFBレジスタアドレス
 * @note JSFBレジスタアドレス, この値は直接使用してはいけない
 * @{
 */
#define D_DU_REG_JSFB_JSESRCTR				0xB1205000		/* JSESRCTR		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSESRLOG				0xB1205004		/* JSESRLOG		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBSRCTR				0xB1205020		/* JSFBSRCTR	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBSYNCCTR			0xB1205030		/* JSFBSYNCCTR	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBSYNCMON			0xB1205034		/* JSFBSYNCMON	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBEN				0xB1205080		/* JSFBEN		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBRF				0xB1205084		/* JSFBRF		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCTR				0xB1205090		/* JSFBCTR		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBMINDLY			0xB1205098		/* JSFBMINDLY	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBRSMD				0xB12050A0		/* JSFBRSMD		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP0L0				0xB1205100		/* JSFBCP0L0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP1L0				0xB1205104		/* JSFBCP1L0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP2L0				0xB1205108		/* JSFBCP2L0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP3L0				0xB120510C		/* JSFBCP3L0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP0L1				0xB1205110		/* JSFBCP0L1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP1L1				0xB1205114		/* JSFBCP1L1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP2L1				0xB1205118		/* JSFBCP2L1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP3L1				0xB120511C		/* JSFBCP3L1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP0L2				0xB1205120		/* JSFBCP0L2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP1L2				0xB1205124		/* JSFBCP1L2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP2L2				0xB1205128		/* JSFBCP2L2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP3L2				0xB120512C		/* JSFBCP3L2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP0L3				0xB1205130		/* JSFBCP0L3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP1L3				0xB1205134		/* JSFBCP1L3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP2L3				0xB1205138		/* JSFBCP2L3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBCP3L3				0xB120513C		/* JSFBCP3L3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBXBAR				0xB1205200		/* JSFBXBAR		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBST				0xB1205300		/* JSFBST		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPFST				0xB1205304		/* JSFBPFST		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPEST				0xB1205308		/* JSFBPEST		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPCST				0xB120530C		/* JSFBPCST		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBEST				0xB1205310		/* JSFBEST		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPECL0				0xB1205320		/* JSFBPECL0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPECL1				0xB1205324		/* JSFBPECL1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPECL2				0xB1205328		/* JSFBPECL2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBPECL3				0xB120532C		/* JSFBPECL3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBFECL0				0xB1205340		/* JSFBFECL0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBFECL1				0xB1205344		/* JSFBFECL1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBFECL2				0xB1205348		/* JSFBFECL2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBFECL3				0xB120534C		/* JSFBFECL3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBDTIML0			0xB1205380		/* JSFBDTIML0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBDTIML1			0xB1205384		/* JSFBDTIML1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBDTIML2			0xB1205388		/* JSFBDTIML2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBDTIML3			0xB120538C		/* JSFBDTIML3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBIRQ				0xB1205400		/* JSFBIRQ		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBIRQC				0xB1205404		/* JSFBIRQC		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBIRQM				0xB1205408		/* JSFBIRQM		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBLMFC				0xB1205500		/* JSFBLMFC		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBLXSYNC			0xB1205504		/* JSFBLXSYNC	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBLALIGN			0xB1205508		/* JSFBLALIGN	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBSTMON				0xB1205F00		/* JSFBSTMON	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBSTLOG				0xB1205F04		/* JSFBSTLOG	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBKLOGL0			0xB1205F10		/* JSFBKLOGL0	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBKLOGL1			0xB1205F14		/* JSFBKLOGL1	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBKLOGL2			0xB1205F18		/* JSFBKLOGL2	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBKLOGL3			0xB1205F1C		/* JSFBKLOGL3	(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBTEST				0xB1205FF0		/* JSFBTEST		(sub6 : o / mmw : -)*/
#define D_DU_REG_JSFB_JSFBMSEL				0xB1205FFC		/* JSFBMSEL		(sub6 : o / mmw : -)*/
/* @} */

/*!
 * @name JSFBレジスタアドレス算出マクロ
 * @note JSFBレジスタアドレス算出マクロ, アドレスはこのマクロを使用する unit は0～3である
 * @{
 */
#define	D_DU_OFT_JSFB_UNIT					0x00000000
#define M_DU_REG_JSFB_GETADDR(ofs, unit)	(UINT)(ofs  + ((unit < 2) ? 0 : D_DU_OFT_JSFB_UNIT))
#define M_DU_REG_JSFB_JSESRCTR(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSESRCTR,unit)
#define M_DU_REG_JSFB_JSESRLOG(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSESRLOG,unit)
#define M_DU_REG_JSFB_JSFBSRCTR(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBSRCTR,unit)
#define M_DU_REG_JSFB_JSFBSYNCCTR(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBSYNCCTR,unit)
#define M_DU_REG_JSFB_JSFBSYNCMON(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBSYNCMON,unit)
#define M_DU_REG_JSFB_JSFBEN(unit)			M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBEN,unit)
#define M_DU_REG_JSFB_JSFBRF(unit)			M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBRF,unit)
#define M_DU_REG_JSFB_JSFBCTR(unit)			M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCTR,unit)
#define M_DU_REG_JSFB_JSFBMINDLY(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBMINDLY,unit)
#define M_DU_REG_JSFB_JSFBRSMD(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBRSMD,unit)
#define M_DU_REG_JSFB_JSFBCP0L0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP0L0,unit)
#define M_DU_REG_JSFB_JSFBCP1L0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP1L0,unit)
#define M_DU_REG_JSFB_JSFBCP2L0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP2L0,unit)
#define M_DU_REG_JSFB_JSFBCP3L0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP3L0,unit)
#define M_DU_REG_JSFB_JSFBCP0L1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP0L1,unit)
#define M_DU_REG_JSFB_JSFBCP1L1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP1L1,unit)
#define M_DU_REG_JSFB_JSFBCP2L1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP2L1,unit)
#define M_DU_REG_JSFB_JSFBCP3L1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP3L1,unit)
#define M_DU_REG_JSFB_JSFBCP0L2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP0L2,unit)
#define M_DU_REG_JSFB_JSFBCP1L2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP1L2,unit)
#define M_DU_REG_JSFB_JSFBCP2L2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP2L2,unit)
#define M_DU_REG_JSFB_JSFBCP3L2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP3L2,unit)
#define M_DU_REG_JSFB_JSFBCP0L3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP0L3,unit)
#define M_DU_REG_JSFB_JSFBCP1L3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP1L3,unit)
#define M_DU_REG_JSFB_JSFBCP2L3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP2L3,unit)
#define M_DU_REG_JSFB_JSFBCP3L3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBCP3L3,unit)
#define M_DU_REG_JSFB_JSFBXBAR(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBXBAR,unit)
#define M_DU_REG_JSFB_JSFBST(unit)			M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBST,unit)
#define M_DU_REG_JSFB_JSFBPFST(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPFST,unit)
#define M_DU_REG_JSFB_JSFBPEST(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPEST,unit)
#define M_DU_REG_JSFB_JSFBPCST(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPCST,unit)
#define M_DU_REG_JSFB_JSFBEST(unit)			M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBEST,unit)
#define M_DU_REG_JSFB_JSFBPECL0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPECL0,unit)
#define M_DU_REG_JSFB_JSFBPECL1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPECL1,unit)
#define M_DU_REG_JSFB_JSFBPECL2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPECL2,unit)
#define M_DU_REG_JSFB_JSFBPECL3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBPECL3,unit)
#define M_DU_REG_JSFB_JSFBFECL0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBFECL0,unit)
#define M_DU_REG_JSFB_JSFBFECL1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBFECL1,unit)
#define M_DU_REG_JSFB_JSFBFECL2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBFECL2,unit)
#define M_DU_REG_JSFB_JSFBFECL3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBFECL3,unit)
#define M_DU_REG_JSFB_JSFBDTIML0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBDTIML0,unit)
#define M_DU_REG_JSFB_JSFBDTIML1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBDTIML1,unit)
#define M_DU_REG_JSFB_JSFBDTIML2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBDTIML2,unit)
#define M_DU_REG_JSFB_JSFBDTIML3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBDTIML3,unit)
#define M_DU_REG_JSFB_JSFBIRQ(unit)			M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBIRQ,unit)
#define M_DU_REG_JSFB_JSFBIRQC(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBIRQC,unit)
#define M_DU_REG_JSFB_JSFBIRQM(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBIRQM,unit)
#define M_DU_REG_JSFB_JSFBLMFC(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBLMFC,unit)
#define M_DU_REG_JSFB_JSFBLXSYNC(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBLXSYNC,unit)
#define M_DU_REG_JSFB_JSFBLALIGN(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBLALIGN,unit)
#define M_DU_REG_JSFB_JSFBSTMON(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBSTMON,unit)
#define M_DU_REG_JSFB_JSFBSTLOG(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBSTLOG,unit)
#define M_DU_REG_JSFB_JSFBKLOGL0(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBKLOGL0,unit)
#define M_DU_REG_JSFB_JSFBKLOGL1(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBKLOGL1,unit)
#define M_DU_REG_JSFB_JSFBKLOGL2(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBKLOGL2,unit)
#define M_DU_REG_JSFB_JSFBKLOGL3(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBKLOGL3,unit)
#define M_DU_REG_JSFB_JSFBTEST(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBTEST,unit)
#define M_DU_REG_JSFB_JSFBMSEL(unit)		M_DU_REG_JSFB_GETADDR(D_DU_REG_JSFB_JSFBMSEL,unit)
/* @} */
#endif
/* @} */
