/*!
 * @skip  $ld:$
 * @file  f_rrh_reg_rfic.h
 * @brief レジスタアドレス定義ヘッダ(rfic)
 * @date  2015/3/30 FJT) Taniguchi
 *
 * All Rights Reserved, Copyright (C) FUJITSU LIMITED 2015
 */

/*!
 * @addtogroup RRH_RRH
 * @{
 */
#ifndef F_RRH_REG_RFIC_H
#define F_RRH_REG_RFIC_H

/*!
 * @name RFICレジスタアドレス for PMC
 * @note RFICレジスタアドレス for PMC
 * @{
 */
#define D_RRH_REG_RFIC_PMC_DEVICE_ID			0x00
#define D_RRH_REG_RFIC_PMC_DEVICE_REV			0x01
#define D_RRH_REG_RFIC_PMC_SPI_CFG				0x02
#define D_RRH_REG_RFIC_PMC_MC_CFG				0x03
#define D_RRH_REG_RFIC_PMC_MAILBOX_CFG			0x04
#define D_RRH_REG_RFIC_PMC_MAILBOX_PARAM0		0x05
#define D_RRH_REG_RFIC_PMC_MAILBOX_PARAM1		0x06
#define D_RRH_REG_RFIC_PMC_MAILBOX_PARAM2		0x07
#define D_RRH_REG_RFIC_PMC_MAILBOX_PARAM3		0x08
#define D_RRH_REG_RFIC_PMC_MAILBOX_CMD			0x09
#define D_RRH_REG_RFIC_PMC_MAILBOX_RESP0		0x0A
#define D_RRH_REG_RFIC_PMC_MAILBOX_RESP1		0x0B
#define D_RRH_REG_RFIC_PMC_MAILBOX_RESP2		0x0C
#define D_RRH_REG_RFIC_PMC_MAILBOX_RESP3		0x0D
#define D_RRH_REG_RFIC_PMC_MAILBOX_RESP4		0x0E
#define D_RRH_REG_RFIC_PMC_MAILBOX_RESP5		0x0F
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_I0		0x10
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_I1		0x11
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_I2		0x12
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_I3		0x13
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_E0		0x14
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_E1		0x15
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_E2		0x16
#define D_RRH_REG_RFIC_PMC_MAILBOX_INT_E3		0x17
#define D_RRH_REG_RFIC_PMC_ERROR_INFO_0			0x1B
#define D_RRH_REG_RFIC_PMC_ERROR_INFO_1			0x1C
/* @} */

/*!
 * @name RFIC MSGID for PMC
 * @note RFIC MSGID for PMC
 * @{
 */
#define	D_RRH_PMC_UNI_MSG_APP_INT_ENABLE_CLEAR						0x0000
#define	D_RRH_PMC_UNI_MSG_APP_INT_ENABLE_SET						0x0001
#define	D_RRH_PMC_UNI_MSG_COMMAND_LOOPBACK							0x0002
#define	D_RRH_PMC_UNI_MSG_DIAGNOSTIC_REG_READ						0x0003
#define	D_RRH_PMC_UNI_MSG_DIAGNOSTIC_REG_WRITE						0x0004
#define	D_RRH_PMC_UNI_MSG_FW_VERSION								0x0005
#define	D_RRH_PMC_UNI_MSG_INITIALIZE								0x0006
#define	D_RRH_PMC_UNI_MSG_ASYNC_ERROR_GET							0x0007
#define	D_RRH_PMC_UNI_MSD204_SYSREF_TRIGGER_ENABLE					0x0100
#define	D_RRH_PMC_UNI_MSG_JESD204_SYSREF_TRIGGER_ENABLE				0x0100
#define	D_RRH_PMC_UNI_MSG_LOSYNC_SEQ								0x0101
#define	D_RRH_PMC_UNI_MSG_LOSYNC_ADJUST								0x0102
#define	D_RRH_PMC_UNI_MSG_LOSYNC_PORT_SELECT						0x0103
#define	D_RRH_PMC_UNI_MSG_FB_BASEBAND_CONFIG						0x0200
#define	D_RRH_PMC_UNI_MSG_FB_BASEBAND_EQFIR_CONFIG					0x0201
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_CONFIG1						0x0202
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_CONFIG2						0x0203
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_CONFIG3						0x0204
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_CONFIG4						0x0205
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_DATA_SOURCE_SELECT			0x0206
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_IO_CONFIG					0x0207
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_TEST_MODE_CONFIG			0x0208
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_TRANSPORT_TEST_CONFIG1		0x0209
#define	D_RRH_PMC_UNI_MSG_FB_JESD204_TX_TRANSPORT_TEST_CONFIG2		0x020A
#define	D_RRH_PMC_UNI_MSG_FB_LO_FREQ_SET							0x020B
#define	D_RRH_PMC_UNI_MSG_FB_RATES_CONFIG							0x020C
#define	D_RRH_PMC_UNI_MSG_FB_RF_IN_CONFIG							0x020D
#define	D_RRH_PMC_UNI_MSG_FB_SIGNAL_CAPT_RAM_READ					0x020E
#define	D_RRH_PMC_UNI_MSG_FB_SIGNAL_CAPT_RAM_WRITE					0x020F
#define	D_RRH_PMC_UNI_MSG_FB_SIGNAL_CAPT_START						0x0210
#define	D_RRH_PMC_UNI_MSG_TEMP_MONITOR_ENABLE						0x0211
#define	D_RRH_PMC_UNI_MSG_TEMP_MONITOR_READ							0x0212
#define	D_RRH_PMC_UNI_MSG_TX_AQM_DC_OFFSET_SET						0x0213
#define	D_RRH_PMC_UNI_MSG_TX_BASEBAND_CONFIG						0x0214
#define	D_RRH_PMC_UNI_MSG_TX_DIGITAL_DC_OFFSET_SET					0x0215
#define	D_RRH_PMC_UNI_MSG_TX_DQM_CONFIG								0x0216
#define	D_RRH_PMC_UNI_MSG_TX_DQM_SELECT								0x0217
#define	D_RRH_PMC_UNI_MSG_TX_ALARM_CONFIG							0x0218
#define	D_RRH_PMC_UNI_MSG_TX_IQI_CORRECT_CONFIG1					0x0219
#define	D_RRH_PMC_UNI_MSG_TX_IQI_CORRECT_CONFIG2					0x021A
#define	D_RRH_PMC_UNI_MSG_TX_IQI_FIR_COEF_APPLY						0x021B
#define	D_RRH_PMC_UNI_MSG_TX_IQI_LOFT_CAL							0x021D
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_8B10B_CONFIG				0x021E
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_8B10B_TEST_JTSPAT_CONFIG	0x021F
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_8B10B_TEST_MODE_CONFIG		0x0220
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_BUFFER_DELAY_CAL			0x0221
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_BUFFER_DELAY_CONFIG			0x0222
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_CONFIG						0x0223
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_IO_CONFIG					0x0224
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_OUTPUT_CAPTURE				0x0225
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_SHORT_TEST_CONFIG			0x0226
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_TEST_MODE_CONFIG			0x0227
#define	D_RRH_PMC_UNI_MSG_TX_LO_FREQ_SET							0x0228
#define	D_RRH_PMC_UNI_MSG_TX_LO_LDO_CONFIG							0x0229
#define	D_RRH_PMC_UNI_MSG_TX_LO_SELECT								0x022A
#define	D_RRH_PMC_UNI_MSG_TX_RATES_CONFIG							0x022B
#define	D_RRH_PMC_UNI_MSG_TX_RF_CONFIG								0x022C
#define	D_RRH_PMC_UNI_MSG_TX_RF_ENABLE_SET							0x022D
#define	D_RRH_PMC_UNI_MSG_TX_SIG_GEN_CONFIG							0x022E
#define	D_RRH_PMC_UNI_MSG_TX_SIG_GEN_PG_RAM_READ					0x022F
#define	D_RRH_PMC_UNI_MSG_TX_SIG_GEN_PG_RAM_WRITE					0x0230
#define	D_RRH_PMC_UNI_MSG_TX_TDD_LOW_POWER_STANDBY_ENABLE			0x0231
#define	D_RRH_PMC_UNI_MSG_FB_POWER_MODE_CONFIG						0x0232
#define	D_RRH_PMC_UNI_MSG_TX_ALARM_OUTPUT_CLEAR						0x0233
#define	D_RRH_PMC_UNI_MSG_TX_TDD_IQI_LOFT_CAL						0x0234
#define	D_RRH_PMC_UNI_MSG_TX_IQI_LOFT_STATUS_READ					0x0235
#define	D_RRH_PMC_UNI_MSG_TX_JESD204_RX_DEBUG						0x0236
#define	D_RRH_PMC_UNI_MSG_TX_IQI_LOFT_FINE_CAL						0x0237
#define	D_RRH_PMC_UNI_MSG_TX_TDD_IQI_LOFT_FINE_CAL					0x0238
#define	D_RRH_PMC_UNI_MSG_TX_PLL_ICP_OVERRIDE						0x0239
/* RX */
#define	D_RRH_PMC_UNI_MSG_RX_AGC_CONFIG								0x0300
#define	D_RRH_PMC_UNI_MSG_RX_AGC_RUN_STATE_CONFIG					0x0301
#define	D_RRH_PMC_UNI_MSG_RX_ANALOG_CONFIG							0x0302
#define	D_RRH_PMC_UNI_MSG_RX_ANALOG_PATH_DELAY_CONFIG				0x0303
#define	D_RRH_PMC_UNI_MSG_RX_BASEBAND_CONFIG						0x0306
#define	D_RRH_PMC_UNI_MSG_RX_GAIN_CTRL_MANUAL_CONFIG				0x0307
#define	D_RRH_PMC_UNI_MSG_RX_GAIN_PARALLEL_IF_CONFIG				0x0309
#define	D_RRH_PMC_UNI_MSG_RX_JESD204_TX_CONFIG1						0x030B
#define	D_RRH_PMC_UNI_MSG_RX_JESD204_TX_CONFIG2						0x030C
#define	D_RRH_PMC_UNI_MSG_RX_JESD204_TX_CONFIG3						0x030D
#define	D_RRH_PMC_UNI_MSG_RX_JESD204_TX_CONFIG4						0x030E
#define	D_RRH_PMC_UNI_MSG_RX_JESD204_TX_IO_CONFIG					0x0310
#define	D_RRH_PMC_UNI_MSG_RX_LO_CONFIG								0x0314
#define	D_RRH_PMC_UNI_MSG_RX_LO_LDO_CONFIG							0x0315
#define	D_RRH_PMC_UNI_MSG_RX_RATES_CONFIG							0x0316
#define	D_RRH_PMC_UNI_MSG_RX_TDD_LOW_POWER_STANDBY_ENABLE			0x031A
#define	D_RRH_PMC_UNI_MSG_RX_TEMP_MONITOR_READ						0x031C
#define	D_RRH_PMC_UNI_MSG_RX_RDPL_CALIB_GAIN_PARAMS_DOWNLOAD		0x031F
#define	D_RRH_PMC_UNI_MSG_RX_RDPL_CALIB_TEMP_SET					0x0321
#define	D_RRH_PMC_UNI_MSG_RX_RDPL_CONFIG_FILE_DOWNLOAD				0x0322
#define	D_RRH_PMC_UNI_MSG_RX_RDPL_MODE_SET							0x0323
#define	D_RRH_PMC_UNI_MSG_RX_RDPL_TEMP_COMPENSATION_SET				0x0326
#define D_RRH_PMC_UNI_MSG_RX_ALARM_CONFIG							0x0327
#define D_RRH_PMC_UNI_MSG_RX_ALARM_OUTPUT_CLEAR						0x0328
#define D_RRH_PMC_UNI_MSG_RX_MIO_MODE								0x0329
#define	D_RRH_PMC_UNI_MSG_RX_AGC_CONFIG2							0x032C
#define	D_RRH_PMC_UNI_MSG_RX_CLIP_DETECT_CONFIG						0x032E
/* @} */

/*!
 * @name RFIC ERRCODE for PMC
 * @note RFIC ERRCODE for PMC
 * @{
 */
/* COMMON */
#define	D_RRH_PMC_UNI_MSG_ERROR_OK                                                             0x0000
#define	D_RRH_PMC_UNI_MSG_ERROR_COMMAND_UNKNOWN                                                0x0001
#define	D_RRH_PMC_UNI_MSG_ERROR_INT_ID                                                         0x0002
#define	D_RRH_PMC_UNI_MSG_ERROR_EFUSE_PARAM_RANGE                                              0x0003
#define	D_RRH_PMC_UNI_MSG_ERROR_SETTING_NOT_IMPLEMENTED                                        0x0004
#define	D_RRH_PMC_UNI_MSG_ERROR_RESP_BITS_OUT_OF_RANGE                                         0x0005
#define	D_RRH_PMC_UNI_MSG_ERROR_GENERAL_TIMER_INVALID_CONFIG                                   0x0006
#define	D_RRH_PMC_UNI_MSG_ERROR_CSU_CALIBRATION_TIMED_OUT                                      0x0007
#define	D_RRH_PMC_UNI_MSG_ERROR_EFUSE_NOT_PROGRAMMED                                           0x0008
#define	D_RRH_PMC_UNI_MSG_ERROR_DIAG_REG_ID_OUT_OF_RANGE                                       0x0009
#define	D_RRH_PMC_UNI_MSG_ERROR_DIAG_REG_NOT_READABLE                                          0x000A
#define	D_RRH_PMC_UNI_MSG_ERROR_DIAG_REG_NOT_WRITABLE                                          0x000B
#define	D_RRH_PMC_UNI_MSG_ERROR_DIAG_REG_PMON_REQ_FAILED                                       0x000C
#define	D_RRH_PMC_UNI_MSG_ERROR_FEATURE_NOT_SUPPORTED                                          0x000D
#define	D_RRH_PMC_UNI_MSG_ERROR_COMMAND_ORDER                                                  0x000E
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_PARAMETER                                              0x000F
#define	D_RRH_PMC_UNI_MSG_ERROR_INCOMPATIBLE_FW_VERSION                                        0x0010
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_RESERVED_VALUE                                         0x0011
#define	D_RRH_PMC_UNI_MSG_ERROR_LO_VCO_FREQ_INIT_FAILED                                        0x0012
#define	D_RRH_PMC_UNI_MSG_ERROR_CANNOT_RUN_COMMAND_CONCURRENTLY                                0x0013
#define	D_RRH_PMC_UNI_MSG_ERROR_TASK_TIMED_OUT                                                 0x0014
#define	D_RRH_PMC_UNI_MSG_ERROR_TDD_CONFLICT                                                   0x0015
#define	D_RRH_PMC_UNI_MSG_ERROR_TASK_QUEUE_QUEUE_OVERFLOW                                      0x0016
#define	D_RRH_PMC_UNI_MSG_ERROR_TASK_QUEUE_QUEUE_UNDERFLOW                                     0x0017
#define	D_RRH_PMC_UNI_MSG_ERROR_UNEXPECTED_GPI_INTERRUPT                                       0x0018
#define	D_RRH_PMC_UNI_MSG_ERROR_MEMORY_ALLOCATION_ERROR_1                                      0x0019
#define	D_RRH_PMC_UNI_MSG_ERROR_MEMORY_ALLOCATION_ERROR_2                                      0x0020
#define	D_RRH_PMC_UNI_MSG_ERROR_MEMORY_FREE_ERROR_1                                            0x0021
#define	D_RRH_PMC_UNI_MSG_ERROR_MEMORY_FREE_ERROR_2                                            0x0022
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_ARM_CONFIG                                             0x0023
#define	D_RRH_PMC_UNI_MSG_ERROR_TIMER_COUNTER_OVERFLOW                                         0x0024
#define	D_RRH_PMC_UNI_MSG_ERROR_CRC_CHECK_FAILED                                               0x0025
#define	D_RRH_PMC_UNI_MSG_ERROR_GENERAL_EXCEPTION_ERROR                                        0x0026
#define	D_RRH_PMC_UNI_MSG_ERROR_WDOG_TIMEOUT                                                   0x0027
#define	D_RRH_PMC_UNI_MSG_ERROR_STACK_CORRUPTED                                                0x0028
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_SYSCLK_FREQ                                            0x0029
#define	D_RRH_PMC_UNI_MSG_ERROR_DECOMPRESSION_ERROR                                            0x0030
#define	D_RRH_PMC_UNI_MSG_ERROR_DCSU_UNABLE_TO_LOCK                                            0x1000
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_HISTOGRAM_ANALYZE_BAD_LIMITS                                0x1001
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_HISTOGRAM_BIN_SATURATION                                    0x1002
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_HISTOGRAM_BIN_UNDERDRIVE                                    0x1003
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_HISTOGRAM_CFG_INVALID_SAMPLE_SIZE                           0x1004
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_HISTOGRAM_CFG_INVALID_PATH                                  0x1005
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_CONSTRAINT                                       0x1006
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_INCONSISTENT_CNVTR_A                             0x1007
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_INCONSISTENT_CNVTR_B                             0x1008
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_INCONSISTENT_INTLV                               0x1009
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_INCONSISTENT_L                                   0x100A
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_INV_INDEX                                        0x100B
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_INV_PARAM                                        0x100C
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_JESD204_TX_LMFC_DELAY_ILLEGAL                               0x100D
#define	D_RRH_PMC_UNI_MSG_ERROR_FREQ_OUT_OF_RANGE                                              0x100E
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_ADJUST_TIMEOUT                                          0x100F
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_AT_LEAST_ONE_PATH_NOT_ENABLED                           0x1010
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_COMMAND_OUT_OF_SEQUENCE                                 0x1011
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_INVALID_LO_FREQ                                         0x1012
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_INVALID_MODE_CONFIG                                     0x1013
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_LO_SELECTED_UNSUPPORTED                                 0x1014
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_MEASUREMENT_TIMEOUT                                     0x1015
#define	D_RRH_PMC_UNI_MSG_ERROR_LOSYNC_NOT_ENABLED                                             0x1016
#define	D_RRH_PMC_UNI_MSG_ERROR_PLL_UNABLE_TO_LOCK                                             0x1017
#define	D_RRH_PMC_UNI_MSG_ERROR_RX_JESD204_TX_LMFC_DELAY_ILLEGAL                               0x1018
#define	D_RRH_PMC_UNI_MSG_ERROR_TXSLICE_INV_PARAM                                              0x1019
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_JESD_TX_NOT_CONFIGURED                   0x101A
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_INVALID_ALERT_TO_WAIT_TRANSITION_COUNT   0x101B
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_INVALID_ALIGN_TO_WAIT_TRANSITION_COUNT   0x101C
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_INVALID_SYSREF_FREQUENCY                 0x101D
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_INVALID_WAIT_TO_ALERT_TRANSITION_COUNT   0x101E
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_SYSREF_SYNC_TIME_OUT                     0x101F
#define	D_RRH_PMC_UNI_MSG_ERROR_CMD_NOT_ABLE_TO_EXE_AT_THIS_TIME                               0x1020
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSREF_TRIGGER_ENABLE_SYSREF_RESET_ERROR                       0x1021
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_DTM_CONFIG                                             0x1022
/* TX */
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH                                                         0x2000
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_BIT_VAL                                             0x2001
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_FB_LO_SEL                                           0x2002
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_TX_LO_SEL                                           0x2003
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_RF_PATH_MASK                                        0x2004
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_PATH_ARM_INDEX                                      0x2005
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_ARM_A_FB_RF_ATTN                                    0x2006
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_ARM_B_FB_RF_ATTN                                    0x2007
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_FINE_FREQ_SHIFT_OUT_OF_RANGE                            0x2008
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_CAL_DAC_I_OFFSET_OUT_OF_RANGE                           0x2009
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_CAL_DAC_Q_OFFSET_OUT_OF_RANGE                           0x200A
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_INVALID_NUMBER_OF_LANES                                0x200B
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_UNSUPPORTED_DAC_CLK_DIVIDER                            0x200C
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_DATA_RATE_UNSUPPORTED                                  0x200D
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_8_LANE_2_CONV_NOT_SUPPORTED                            0x200E
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_INVALID_INTERP_FACTOR                                  0x200F
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_ARM_A_FB_SOURCE                                     0x2010
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_ARM_B_FB_SOURCE                                     0x2011
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_CPGEN_LOCK_TIMED_OUT                                    0x2012
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_CSU_LOCK_TIMED_OUT                                      0x2013
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_IQI_FILTER_INDEX                                        0x2014
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_IQI_DC_SATURATED                                        0x2015
#define	D_RRH_PMC_UNI_MSG_ERROR_UNABLE_TO_READ_WHEN_SIG_GEN_ACTIVE                             0x2016
#define	D_RRH_PMC_UNI_MSG_ERROR_UNABLE_TO_WRITE_WHEN_SIG_GEN_ACTIVE                            0x2017
#define	D_RRH_PMC_UNI_MSG_ERROR_VCO_FREQ_UNSUPPORTED_REV_A                                     0x2018
#define	D_RRH_PMC_UNI_MSG_ERROR_SERDES_ADCOC_LOCK_GAIN_FAILED                                  0x2019
#define	D_RRH_PMC_UNI_MSG_ERROR_SERDES_ADCOC_PROG_REF_FAILED                                   0x201A
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_DAC_CLK_DIVDER_UNINITIALIZED                           0x201B
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_ADDITIONAL_RBD_OUT_OF_RANGE                            0x201C
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_DQM_NOT_CONFIGURED                                     0x201D
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPAHT_INV_ZIF_DQM_CONFIGURATION                               0x201E
#define	D_RRH_PMC_UNI_MSG_ERROR_TX_PATH_INVALID_LO_SOURCE_CONFIG                               0x201F
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_FEEDBACK_LO_NOT_CONFIGURED                              0x2020
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_TXMIXER_NOT_CONFIGURED                                  0x2021
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_USEAGE_IN_DC_COUPLED_MODE                           0x2022
#define	D_RRH_PMC_UNI_MSG_ERROR_TXPATH_INV_USEAGE_IN_AC_COUPLED_MODE                           0x2023
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX                                                     0x2100
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_TX_SRC_CFG                                             0x2101
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX_INV_LANE_USE_MODE                                   0x2102
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX_INV_PARAM                                           0x2103
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX_INV_CHAR_CLK_DIV                                    0x2104
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX_BUFFER_DELAY_CAL                                    0x2105
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX_OUTPUT_CAPTURE                                      0x2106
#define	D_RRH_PMC_UNI_MSG_ERROR_JESD204_RX_SIG_GEN_BUSY                                        0x2107
#define	D_RRH_PMC_UNI_MSG_ERROR_FBPATH                                                         0x2200
#define	D_RRH_PMC_UNI_MSG_ERROR_PREV_CAL_IN_PROGRESS                                           0x2201
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_CAPTURE_RAM_CFG                                        0x2202
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_RAM_ADDR_INDEX_RANGE                                   0x2203
#define	D_RRH_PMC_UNI_MSG_ERROR_INVALID_FB_RATE_CFG                                            0x2204
#define	D_RRH_PMC_UNI_MSG_ERROR_UNSUPPORTED_FB_RATE                                            0x2205
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_INVALID_PATH_ARM_INDEX                                      0x2206
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_INVALID_ADC_CLK_DIV                                         0x2207
#define	D_RRH_PMC_UNI_MSG_ERROR_FBPATH_CSU_LOCK_TIMED_OUT                                      0x2208
#define	D_RRH_PMC_UNI_MSG_ERROR_ADC_OFFSET_CAL_TIMED_OUT                                       0x2209
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_CAPTURE_RAM_TIMED_OUT                                       0x220A
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_INVALID_PATH_ARM_CFG                                        0x220B
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_INVALID_DECIMATION_FACTOR                                   0x220C
#define	D_RRH_PMC_UNI_MSG_ERROR_FB_ADC_DUTY_CYCLE_CAL_FAIL                                     0x220D
#define	D_RRH_PMC_UNITX_MSG_ERROR_IQI_LOFT_CAL                                                 0x2300
#define	D_RRH_PMC_UNITX_MSG_ERROR_IQI_LOFT_CAL_DQM_FREQ_INVALID                                0x2301
#define	D_RRH_PMC_UNITX_MSG_ERROR_IQI_LOFT_CAL_DQM_OFFSET_FREQ_OUT_OF_RANGE                    0x2302
#define	D_RRH_PMC_UNITX_MSG_ERROR_IQI_LOFT_CAL_DQM_OFFSET_FREQ_LARGER_THAN_DQM_FREQ            0x2303
#define	D_RRH_PMC_UNITX_MSG_ERROR_IQI_LOFT_CAL_INVALID_ADC_RATE_FOR_IQI_CALIB                  0x2304
#define	D_RRH_PMC_UNITX_MSG_ERROR_IQI_LOFT_CAL_NUM_ITERATIONS_INVALID                          0x2305
#define	D_RRH_PMC_UNITX_MSG_ERROR_TDD_IQI_LOFT_CAL                                             0x2400
#define	D_RRH_PMC_UNITX_MSG_ERROR_TDD_IQI_LOFT_CAL_CALIBRATION_IN_PROGRESS                     0x2401
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSTEM                                                         0x2500
#define	D_RRH_PMC_UNI_MSG_ERROR_SYSTEM_TDD_PROCESSING_FAILED                                   0x2501
/* RX ? */
/* @} */

/*!
 * @name RFIC DIAG REG for PMC
 * @note RFIC DIAG REG for PMC
 * @{
 */
#define	D_RRH_PMC_UNITX_DIAG_REG_SERIAL_NUMBER1                               0
#define	D_RRH_PMC_UNITX_DIAG_REG_SERIAL_NUMBER2                               1
#define	D_RRH_PMC_UNITX_DIAG_REG_SERIAL_NUMBER3                               2
#define	D_RRH_PMC_UNITX_DIAG_REG_FSYSCLK                                      3
#define	D_RRH_PMC_UNITX_DIAG_REG_TX_LO                                        4
#define	D_RRH_PMC_UNITX_DIAG_REG_FB_LO                                        5
#define	D_RRH_PMC_UNITX_DIAG_REG_SERDES_RX_CSU                                6
#define	D_RRH_PMC_UNITX_DIAG_REG_SERDES_TX_CSU                                7
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN0                     8
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN1                     9
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN2                     10
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN3                     11
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN4                     12
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN5                     13
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN6                     14
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LN7                     15
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN0         16
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN1         17
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN2         18
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN3         19
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN4         20
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN5         21
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN6         22
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_BIT_ERR_CNT_LN7         23
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN0         24
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN1         25
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN2         26
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN3         27
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN4         28
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN5         29
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN6         30
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_LCV_ERR_CNT_LN7         31
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN0              32
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN1              33
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN2              34
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN3              35
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN4              36
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN5              37
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN6              38
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_LN7              39
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN0  40
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN1  41
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN2  42
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN3  43
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN4  44
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN5  45
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN6  46
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_DEC_8B10B_JTSPAT_BIT_ERR_CNT_LN7  47
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN0                 48
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN1                 49
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN2                 50
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN3                 51
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN4                 52
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN5                 53
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN6                 54
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_CODE_GRP_SYNC_LN7                 55
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN0                           56
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN1                           57
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN2                           58
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN3                           59
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN4                           60
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN5                           61
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN6                           62
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ILA_LN7                           63
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN0                    64
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN1                    65
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN2                    66
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN3                    67
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN4                    68
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN5                    69
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN6                    70
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_SYNC_LN7                    71
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN0                     72
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN1                     73
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN2                     74
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN3                     75
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN4                     76
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN5                     77
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN6                     78
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FRAME_MON_LN7                     79
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN0                    80
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN1                    81
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN2                    82
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN3                    83
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN4                    84
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN5                    85
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN6                    86
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HANDLE_LN7                    87
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN0                 88
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN1                 89
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN2                 90
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN3                 91
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN4                 92
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN5                 93
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN6                 94
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_ERR_HNDLG_CNT_LN7                 95
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_SYNCB                             96
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_LTST                              97
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_STST                              98
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_RX_FIFO                              99
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_ILA_COMPLETE                      100
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_SYNCB                             101
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_SYNCB_ERR_CNTR                    102
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_SEND_A_SEND_F                     103
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_A_INS_CNTR_LN0                    104
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_A_INS_CNTR_LN1                    105
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_F_INS_CNTR_LN0                    106
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_F_INS_CNTR_LN1                    107
#define	D_RRH_PMC_UNITX_DIAG_REG_JESD204_TX_FIFO                              108
#define	D_RRH_PMC_UNITX_DIAG_REG_SYSREF_SYNC                                  109
/* @} */
#endif
/* @} */
