all: alllib 
clean: allclean

alllib:
	#ft_com
	cd ../ft_com/api/makefile;make
	#ft_dhcp
	cd ../ft_dhcp/api/makefile;make
	#ft_ptp
	cd ../ft_ptp/api/makefile;make
	#ft_rfp
	cd ../ft_rfp/api/makefile;make
	#ft_eqs
	cd ../ft_eqs/api/makefile;make
	#ft_eio
	cd ../ft_eio/api/makefile;make

allclean:
	#ft_com
	cd ../ft_com/api/makefile;make clean
	#ft_dhcp
	cd ../ft_dhcp/api/makefile;make clean
	#ft_ptp
	cd ../ft_ptp/api/makefile;make clean
	#ft_rfp
	cd ../ft_rfp/api/makefile;make clean
	#ft_eio
	cd ../ft_eio/api/makefile;make clean
	#ft_eqs
	cd ../ft_eqs/api/makefile;make clean
