/******************************************************************************************************************************/
/**
 *  @skip	$Id:$
 *  @file
 *  @brief	Constant Value Definition(Message ID)
 *  @note	NOTE THAT YOU MUST NOT EDIT THIS FILE MANUALLY, which is automatically generated with VBA macro. \n
 * 			See also FBIF_llsDU_cm_Server_MSI_O_RAN_SOFTWARE_MANAGEMENT.xlsm
 * 
 *  ALL Rights Reserved, Copyright (c) FUJITSU Limited 2013-2018
 */
/******************************************************************************************************************************/

#ifndef	F_MPSW_MSG_O_RAN_SOFTWARE_MANAGEMENT_DEF_H
#define	F_MPSW_MSG_O_RAN_SOFTWARE_MANAGEMENT_DEF_H

/** @addtogroup Message0x_o_ran_software_management
 *  @{
 */

#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INVENTROY_GET_REQ	0x811e0111U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INVENTROY_GET_REQ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INVENTROY_GET_CFM	0x811e0112U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INVENTROY_GET_CFM  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INVENTROY_GET_REJ	0x811e0113U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INVENTROY_GET_REJ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_REQ	0x811e0611U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_REQ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_CFM	0x811e0612U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_CFM  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_REJ	0x811e0613U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_REJ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_REQ	0x811e0621U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_REQ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_CFM	0x811e0622U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_CFM  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_REJ	0x811e0623U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_REJ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_REQ	0x811e0631U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_REQ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_CFM	0x811e0632U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_CFM  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_REJ	0x811e0633U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_REJ  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_NTF_IND	0x811e0715U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_DOWNLOAD_NFT_IND  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_NTF_IND	0x811e0725U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_INSTALL_NFT_IND  */
#define	D_MSG_MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_NTF_IND	0x811e0735U
															/**< MSI_O_RAN_SOFTWARE_MANAGEMENT_ACTIVATE_NFT_IND  */

/** @} */

#endif	/* F_MPSW_MSG_O_RAN_SOFTWARE_MANAGEMENT_DEF_H */
