
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2019, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 18.10-15

    YumaPro SIL-SA module
    module o-ran-externalio
    revision 2019-02-04
    namespace urn:o-ran:external-io:1.0
    organization O-RAN Alliance
    Created: 2019-12-20T02:20:28Z
    CLI parameters:
        format yc
        indent 4
        module o-ran-externalio
        output y_o-ran-externalio.c
        sil-get2
        sil-sa
        unified true

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_not.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "ses.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_util.h"
#include "xml_val.h"
#include "u_o-ran-externalio.h"
#include "y_o-ran-externalio.h"

/* module static variables */
static ncx_module_t *o_ran_externalio_mod;
static obj_template_t *external_io_obj;
static val_value_t *external_io_val;

/********************************************************************
* FUNCTION y_o_ran_externalio_init_static_vars
*
* initialize module static variables
*
********************************************************************/
static void y_o_ran_externalio_init_static_vars (void)
{
    o_ran_externalio_mod = NULL;
    external_io_obj = NULL;
    external_io_val = NULL;

} /* y_o_ran_externalio_init_static_vars */

/********************************************************************
* FUNCTION o_ran_externalio_external_io_input_get
*
* Get database object callback for list input
* Path: /external-io/input
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t o_ran_externalio_external_io_input_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* local key o-ran-externalio:name */
    const xmlChar *k_external_io_input_name = 0;
    boolean name_fixed = FALSE;
    boolean name_present = FALSE;
    keyval = getcb_find_key_str(get2cb,
        y_o_ran_externalio_M_o_ran_externalio,
        y_o_ran_externalio_N_name);
    if (keyval) {
        k_external_io_input_name = VAL_STRING(keyval);
        name_fixed = VAL_IS_FIXED_VALUE(keyval);
        name_present = TRUE;
    }

    return u_o_ran_externalio_external_io_input_get(
        get2cb,
        k_external_io_input_name,
        name_fixed,
        name_present);

} /* o_ran_externalio_external_io_input_get */

/********************************************************************
* FUNCTION o_ran_externalio_external_io_output_get
*
* Get database object callback for list output
* Path: /external-io/output
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
static status_t o_ran_externalio_external_io_output_get (
    ses_cb_t *scb,
    xml_msg_hdr_t *msg,
    getcb_get2_t *get2cb)
{

    (void)scb;
    (void)msg;
    val_value_t *keyval = NULL;

    /* local key o-ran-externalio:name */
    const xmlChar *k_external_io_output_name = 0;
    boolean name_fixed = FALSE;
    boolean name_present = FALSE;
    keyval = getcb_find_key_str(get2cb,
        y_o_ran_externalio_M_o_ran_externalio,
        y_o_ran_externalio_N_name);
    if (keyval) {
        k_external_io_output_name = VAL_STRING(keyval);
        name_fixed = VAL_IS_FIXED_VALUE(keyval);
        name_present = TRUE;
    }

    return u_o_ran_externalio_external_io_output_get(
        get2cb,
        k_external_io_output_name,
        name_fixed,
        name_present);

} /* o_ran_externalio_external_io_output_get */


/********************************************************************
* FUNCTION o_ran_externalio_external_io_output_setting_line_out_edit
*
* Edit database object callback
* Path: /external-io/output-setting/line-out
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t o_ran_externalio_external_io_output_setting_line_out_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* ancestor key o-ran-externalio:name */
    const xmlChar *k_external_io_output_setting_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter o_ran_externalio_external_io_output_setting_line_out_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_o_ran_externalio_external_io_output_setting_line_out_edit(scb, msg, cbtyp, editop, newval, curval,
        k_external_io_output_setting_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* o_ran_externalio_external_io_output_setting_line_out_edit */


/********************************************************************
* FUNCTION o_ran_externalio_external_io_output_setting_edit
*
* Edit database object callback
* Path: /external-io/output-setting
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t o_ran_externalio_external_io_output_setting_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    /* local key o-ran-externalio:name */
    const xmlChar *k_external_io_output_setting_name =
        VAL_STRING(sil_sa_get_key(msg, 1));

    if (LOGDEBUG) {
        log_debug("\nEnter o_ran_externalio_external_io_output_setting_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_o_ran_externalio_external_io_output_setting_edit(scb, msg, cbtyp, editop, newval, curval,
        k_external_io_output_setting_name);

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* o_ran_externalio_external_io_output_setting_edit */


/********************************************************************
* FUNCTION o_ran_externalio_external_io_edit
*
* Edit database object callback
* Path: /external-io
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
static status_t o_ran_externalio_external_io_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    val_value_t *errorval = (curval) ? curval : newval;
    uint32 cur_errs = agt_get_error_count(msg);

    if (LOGDEBUG) {
        log_debug("\nEnter o_ran_externalio_external_io_edit callback for %s phase",
            agt_cbtype_name(cbtyp));
    }

    res = u_o_ran_externalio_external_io_edit(scb, msg, cbtyp, editop, newval, curval);

    if (res == NO_ERR && cbtyp == AGT_CB_COMMIT) {
        res = agt_check_cache(&external_io_val, newval, curval, editop);
    }
    

    if ((res != NO_ERR) && (cur_errs == agt_get_error_count(msg))) {
        agt_record_error(
            scb,
            &msg->mhdr,
            NCX_LAYER_CONTENT,
            res,
            NULL,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval,
            (errorval) ? NCX_NT_VAL : NCX_NT_NONE,
            errorval);
    }
    return res;

} /* o_ran_externalio_external_io_edit */

/********************************************************************
* FUNCTION y_o_ran_externalio_init
*
* initialize the o-ran-externalio server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t y_o_ran_externalio_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;

    y_o_ran_externalio_init_static_vars();

    /* change if custom handling done */
    if (xml_strcmp(modname, y_o_ran_externalio_M_o_ran_externalio)) {
        return ERR_NCX_UNKNOWN_MODULE;
    }

    if (revision && xml_strcmp(revision, y_o_ran_externalio_R_o_ran_externalio)) {
        return ERR_NCX_WRONG_VERSION;
    }


    res = ncxmod_load_module(
        y_o_ran_externalio_M_o_ran_externalio,
        y_o_ran_externalio_R_o_ran_externalio,
        agt_get_savedevQ(),
        &o_ran_externalio_mod);
    if (res != NO_ERR) {
        return res;
    }

    external_io_obj = ncx_find_object(
        o_ran_externalio_mod,
        y_o_ran_externalio_N_external_io);
    if (external_io_obj == NULL) {
        return ERR_NCX_DEF_NOT_FOUND;
    }

    res = agt_cb_register_callback(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io",
        y_o_ran_externalio_R_o_ran_externalio,
        o_ran_externalio_external_io_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:input",
        y_o_ran_externalio_R_o_ran_externalio,
        o_ran_externalio_external_io_input_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_get_callback(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:output",
        y_o_ran_externalio_R_o_ran_externalio,
        o_ran_externalio_external_io_output_get);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:output-setting",
        y_o_ran_externalio_R_o_ran_externalio,
        o_ran_externalio_external_io_output_setting_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = agt_cb_register_callback(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:output-setting/o-ran-io:line-out",
        y_o_ran_externalio_R_o_ran_externalio,
        o_ran_externalio_external_io_output_setting_line_out_edit);
    if (res != NO_ERR) {
        return res;
    }

    res = u_o_ran_externalio_init(modname, revision);
    return res;

} /* y_o_ran_externalio_init */

/********************************************************************
* FUNCTION y_o_ran_externalio_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t y_o_ran_externalio_init2 (void)
{
    status_t res = NO_ERR;

    res = u_o_ran_externalio_init2();

    return res;

} /* y_o_ran_externalio_init2 */

/********************************************************************
* FUNCTION y_o_ran_externalio_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void y_o_ran_externalio_cleanup (void)
{

    agt_cb_unregister_callbacks(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io");

    agt_cb_unregister_callbacks(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:input");

    agt_cb_unregister_callbacks(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:output");

    agt_cb_unregister_callbacks(
        y_o_ran_externalio_M_o_ran_externalio,
        (const xmlChar *)"/o-ran-io:external-io/o-ran-io:output-setting");
    u_o_ran_externalio_cleanup();

} /* y_o_ran_externalio_cleanup */

/* END SIL-SA y_o_ran_externalio.c */
