/********************************************************************************************************************/
/**
 *  @skip   $Id:$
 *  @file     m_rc_rom.c
 *  @brief   declare  ROM table in RCT task
 *  @date   2008/07/25 FFCS)linlj create
 *  @date   2009/08/08 FFCS)Wangjuan modify for
 *							  CR-00054-005(CPRI spec V1.0.8)
 *  @date   2009/10/08 QNET)Kabasima MOD CR-00071-001(TRA-HS-V2R11 RE AUTO RESET and 3GRF-INF)
 *  @date   2010/02/19 QNET)Kabasima CR-xxxxx-xxx [DCM向け]TS-145-ALM制御時のRE動作の件
 *  @date   2010/06/01 FJT)Taniguchi CR-00091-001:[DCM向け]RE HSIF仕様書v2.18版リリース
 *  @date   2011/04/08 FJT)Koshida modify for TS137対応(リソースALM時の故障状態/基本機能監視項目見直し)
 *  @date   2011/05/13 FJT)koshida modify for CeNB-F-073-008(F)(REにおける故障発生時の機能部状態報告)
 *  @date   2011/10/10 FFCS)Linlj  modify for 省電力対応
 *  @date   2012/03/15 ALP)Yamamoto M-S3G-eNBSYS-02601：(12A-01-006)SLC-RRE ALM/ERRコード変更
 *  @date   2015/04/21 FFCS)yuzhh modify for TDD-SRE
 *  @date   2015/06/23 ALP)Ueda modify for TDD-SRE(Zynq)
 *  @date   2015/11/30 TDIPS)Watanabe sfpテーブル修正
 *  ALL Rights Reserved, Copyright (c) FUJITSU Limited 2008-2015
 */
/********************************************************************************************************************/

/** @addtogroup RRH_L3_RCT
 * @{ */

/********************************************************************************************************************/
/* include file																										*/
/********************************************************************************************************************/
#include "f_rrh_def.h"
#include "m_cm_header.h"
#include "m_rc_header.h"

/********************************************************************************************************************/
/**
 *  @brief     declare BCD character convert  table in RCT task
 *  @note     declare BCD character convert  table in RCT task
 *  @param  None
 *  @return   None
 *  @retval   -
 *  @date     2008/07/25 FFCS)linlj create
 */
UCHAR		rcr_bcd_cvt_tbl[ CMD_NUM16 ] =
{
	'0',							/* 0	*/
	'1',							/* 1	*/
	'2',							/* 2	*/
	'3',							/* 3	*/
	'4',							/* 4	*/
	'5',							/* 5	*/
	'6',							/* 6	*/
	'7',							/* 7	*/
	'8',							/* 8	*/
	'9',							/* 9	*/
	'A',							/* A	*/
	'B',							/* B	*/
	'C',							/* C	*/
	'D',							/* D	*/
	'E',							/* E	*/
	'F'							/* F	*/
};

/** RE card status report(SV-error) - ERROR code conversion */
USHORT		rcr_sverr_cvt_tbl[RCD_ERRCODE_SEAR_LEN] [CMD_NUM3]=
{
	/* SV error index      ERROR CODE  				SYSTEM			*/	/* error code */
	{	CMD_NUM28,		CMD_ERRCD_DL_FILINFO	, CMD_SYS_S3G},
	{	CMD_NUM27,		CMD_ERRCD_DL_FILDAT		, CMD_SYS_S3G},
	{	CMD_NUM24,		CMD_ERRCD_BR3_SLEEP		, CMD_SYS_S3G},
	{	CMD_NUM23,		CMD_ERRCD_BR2_SLEEP		, CMD_SYS_S3G},
	{	CMD_NUM22,		CMD_ERRCD_BR1_SLEEP		, CMD_SYS_S3G},
	{	CMD_NUM21,		CMD_ERRCD_BR0_SLEEP		, CMD_SYS_S3G},
	{	CMD_NUM20,		CMD_ERRCD_AMP_POWOFF	, CMD_SYS_S3G},
};



/** RE card status report(FB BR) */
USHORT		rcr_cardFb_br_rscalm_tbl[RCD_FB_RESALM_NUM] [CMD_NUM4]=
{
	{D_RRH_ALMCD_FWPLLBR0			,RCD_FB_TRX	 	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBPLLBR0     		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXPLLBR0     		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC1BR0    		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC2BR0    		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWJESDBR0    		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBJESDBR0    		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXJESDBR0    		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW1BR0     		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW2BR0     		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TXGABR0    		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TOVEBR0      		,RCD_FB_TRX  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXGABR0    		,RCD_FB_LNA  	,RCD_TRA_BR0 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWPLLBR1			,RCD_FB_TRX	 	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBPLLBR1     		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXPLLBR1     		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC1BR1    		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC2BR1    		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWJESDBR1    		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBJESDBR1    		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXJESDBR1    		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW1BR1     		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW2BR1     		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TXGABR1    		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TOVEBR1      		,RCD_FB_TRX  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXGABR1    		,RCD_FB_LNA  	,RCD_TRA_BR1 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWPLLBR2			,RCD_FB_TRX	 	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBPLLBR2     		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXPLLBR2     		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC1BR2    		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC2BR2    		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWJESDBR2    		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBJESDBR2    		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXJESDBR2    		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW1BR2     		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW2BR2     		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TXGABR2    		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TOVEBR2      		,RCD_FB_TRX  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXGABR2    		,RCD_FB_LNA  	,RCD_TRA_BR2 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWPLLBR3			,RCD_FB_TRX	 	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBPLLBR3     		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXPLLBR3     		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC1BR3    		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RFIC2BR3			,RCD_FB_TRX		,RCD_TRA_BR3	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FWJESDBR3			,RCD_FB_TRX		,RCD_TRA_BR3	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_FBJESDBR3    		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXJESDBR3    		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW1BR3     		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TDDSW2BR3     		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TXGABR3    		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_TOVEBR3      		,RCD_FB_TRX  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH},
	{D_RRH_ALMCD_RXGABR3    		,RCD_FB_LNA  	,RCD_TRA_BR3 	,RCD_FB_ALM_HIGH}
};/* *** RCD_FB_RESALM_NUM is 40 now, if size change, remember to modify it too */

/** RE carrier status report(FB) */
RCT_CARDFB_BR_CARALM_T	rcr_cardFb_br_caralm_tbl[RCD_FB_CARALM_NUM]=
{
	{D_RRH_ALMCD_REMOTEALM,		RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},

	{D_RRH_ALMCD_PLLNG,			RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},
	{D_RRH_ALMCD_FPGANG1,		RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},
	{D_RRH_ALMCD_FPGANG2,		RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},

	{D_RRH_ALMCD_FPGAIF1,		RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},
	{D_RRH_ALMCD_FPGAIF2,		RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},
	{D_RRH_ALMCD_CPLDIF1,		RCD_FB_TRX_INF,		CMD_NT4R_BR_BIT,	RCD_CARALM_222},
	{D_RRH_ALMCD_TEMP,			RCD_FB_TRX,			CMD_NT4R_BR_BIT,	RCD_CARALM_221},
	{D_RRH_ALMCD_PSALM,			RCD_FB_T_PA,		CMD_NT4R_BR_BIT,	RCD_CARALM_221},

	{D_RRH_ALMCD_RFIC1BR0,		RCD_FB_TRX,			CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC1BR0)},
	{D_RRH_ALMCD_RFIC2BR0,		RCD_FB_TRX,			CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC2BR0)},
	{D_RRH_ALMCD_FWJESDBR0,		RCD_FB_TRX, 		CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FWJESDBR0)},
	{D_RRH_ALMCD_FBJESDBR0, 	RCD_FB_TRX, 		CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FBJESDBR0)},
	{D_RRH_ALMCD_RXJESDBR0, 	RCD_FB_TRX, 		CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXJESDBR0)},
	{D_RRH_ALMCD_TXGABR0,		RCD_FB_TRX, 		CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TXGABR0)},
	{D_RRH_ALMCD_TOVEBR0,		RCD_FB_TRX, 		CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TOVEBR0)},
	{D_RRH_ALMCD_RXGABR0,		RCD_FB_LNA, 		CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXGABR0)},
	{D_RRH_ALMCD_TDDSW1BR0,		RCD_FB_TRX,			CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW1BR0)},
	{D_RRH_ALMCD_TDDSW2BR0,		RCD_FB_TRX,			CMD_BR0_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW2BR0)},

	{D_RRH_ALMCD_RFIC1BR1,		RCD_FB_TRX,			CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC1BR1)},
	{D_RRH_ALMCD_RFIC2BR1,		RCD_FB_TRX,			CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC2BR1)},
	{D_RRH_ALMCD_FWJESDBR1,		RCD_FB_TRX, 		CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FWJESDBR1)},
	{D_RRH_ALMCD_FBJESDBR1, 	RCD_FB_TRX, 		CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FBJESDBR1)},
	{D_RRH_ALMCD_RXJESDBR1, 	RCD_FB_TRX, 		CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXJESDBR1)},
	{D_RRH_ALMCD_TXGABR1,		RCD_FB_TRX, 		CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TXGABR1)},
	{D_RRH_ALMCD_TOVEBR1,		RCD_FB_TRX, 		CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TOVEBR1)},
	{D_RRH_ALMCD_RXGABR1,		RCD_FB_LNA, 		CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXGABR1)},
	{D_RRH_ALMCD_TDDSW1BR1,		RCD_FB_TRX,			CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW1BR1)},
	{D_RRH_ALMCD_TDDSW2BR1,		RCD_FB_TRX,			CMD_BR1_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW2BR1)},

	{D_RRH_ALMCD_RFIC1BR2,		RCD_FB_TRX,			CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC1BR2)},
	{D_RRH_ALMCD_RFIC2BR2,		RCD_FB_TRX,			CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC2BR2)},
	{D_RRH_ALMCD_FWJESDBR2,		RCD_FB_TRX, 		CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FWJESDBR2)},
	{D_RRH_ALMCD_FBJESDBR2, 	RCD_FB_TRX, 		CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FBJESDBR2)},
	{D_RRH_ALMCD_RXJESDBR2, 	RCD_FB_TRX, 		CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXJESDBR2)},
	{D_RRH_ALMCD_TXGABR2,		RCD_FB_TRX, 		CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TXGABR2)},
	{D_RRH_ALMCD_TOVEBR2,		RCD_FB_TRX, 		CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TOVEBR2)},
	{D_RRH_ALMCD_RXGABR2,		RCD_FB_LNA, 		CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXGABR2)},
	{D_RRH_ALMCD_TDDSW1BR2,		RCD_FB_TRX,			CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW1BR2)},
	{D_RRH_ALMCD_TDDSW2BR2,		RCD_FB_TRX,			CMD_BR2_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW2BR2)},

	{D_RRH_ALMCD_RFIC1BR3,		RCD_FB_TRX,			CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC1BR3)},
	{D_RRH_ALMCD_RFIC2BR3,		RCD_FB_TRX,			CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RFIC2BR3)},
	{D_RRH_ALMCD_FWJESDBR3,		RCD_FB_TRX, 		CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FWJESDBR3)},
	{D_RRH_ALMCD_FBJESDBR3, 	RCD_FB_TRX, 		CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_FBJESDBR3)},
	{D_RRH_ALMCD_RXJESDBR3, 	RCD_FB_TRX, 		CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXJESDBR3)},
	{D_RRH_ALMCD_TXGABR3,		RCD_FB_TRX, 		CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TXGABR3)},
	{D_RRH_ALMCD_TOVEBR3,		RCD_FB_TRX, 		CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TOVEBR3)},
	{D_RRH_ALMCD_RXGABR3,		RCD_FB_LNA, 		CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_RXGABR3)},
	{D_RRH_ALMCD_TDDSW1BR3,		RCD_FB_TRX,			CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW1BR3)},
	{D_RRH_ALMCD_TDDSW2BR3,		RCD_FB_TRX,			CMD_BR3_BIT,		RCD_CARALM_CONV(D_RRH_ALMCD_TDDSW2BR3)}

};

/**	PLL Alarm code define table */
USHORT	rcr_pllalmcode[RCD_PLLALM_NUM] =
{
		D_RRH_ALMCD_PLLNG
};


/**	CPRI Alarm code define table */
USHORT	rcr_cprialmcode[RCD_CPRIALM_NUM] =
{
		D_RRH_ALMCD_FPGANG1,
		D_RRH_ALMCD_FPGANG2,
		D_RRH_ALMCD_FPGANG3
};


/**	APD COM Alarm code define table */
USHORT	rcr_apdcomalmcode[RCD_APDALM_LOOP_NUM] =
{
		D_RRH_ALMCD_RFIC1,
		D_RRH_ALMCD_RFIC2,
		D_RRH_ALMCD_RFIC3,
		D_RRH_ALMCD_RFIC4,
		D_RRH_ALMCD_RFICIF1,
		D_RRH_ALMCD_RFICIF2,
		D_RRH_ALMCD_RFICIF3,
		D_RRH_ALMCD_RFICIF4,
		D_RRH_ALMCD_CPLDIF1,
		D_RRH_ALMCD_DUM8,
		D_RRH_ALMCD_TEMP,
		D_RRH_ALMCD_FPGAIF1,
		D_RRH_ALMCD_FPGAIF2,
		D_RRH_ALMCD_DUM9,
		D_RRH_ALMCD_PSALM,
		D_RRH_ALMCD_DUM10
};


/**	APD0 Alarm code define table */
USHORT	rcr_apd0almcode[RCD_APDALM_LOOP_NUM] =
{
		D_RRH_ALMCD_DUM21,
		D_RRH_ALMCD_FWPLLBR0,
		D_RRH_ALMCD_FBPLLBR0,
		D_RRH_ALMCD_RXPLLBR0,
		D_RRH_ALMCD_RFIC1BR0,
		D_RRH_ALMCD_RFIC2BR0,
		D_RRH_ALMCD_FWJESDBR0,
		D_RRH_ALMCD_FBJESDBR0,
		D_RRH_ALMCD_RXJESDBR0,
		D_RRH_ALMCD_DUM22,
		D_RRH_ALMCD_TXGABR0,
		D_RRH_ALMCD_TOVEBR0,
		D_RRH_ALMCD_RXGABR0,
		D_RRH_ALMCD_TDDSW1BR0,
		D_RRH_ALMCD_TDDSW2BR0,
		D_RRH_ALMCD_TDDSW3BR0
};


/**	APD1 Alarm code define table */
USHORT	rcr_apd1almcode[RCD_APDALM_LOOP_NUM] =
{
		D_RRH_ALMCD_DUM23,
		D_RRH_ALMCD_FWPLLBR1,
		D_RRH_ALMCD_FBPLLBR1,
		D_RRH_ALMCD_RXPLLBR1,
		D_RRH_ALMCD_RFIC1BR1,
		D_RRH_ALMCD_RFIC2BR1,
		D_RRH_ALMCD_FWJESDBR1,
		D_RRH_ALMCD_FBJESDBR1,
		D_RRH_ALMCD_RXJESDBR1,
		D_RRH_ALMCD_DUM24,
		D_RRH_ALMCD_TXGABR1,
		D_RRH_ALMCD_TOVEBR1,
		D_RRH_ALMCD_RXGABR1,
		D_RRH_ALMCD_TDDSW1BR1,
		D_RRH_ALMCD_TDDSW2BR1,
		D_RRH_ALMCD_TDDSW3BR1
};

/**	APD2 Alarm code define table */
USHORT	rcr_apd2almcode[RCD_APDALM_LOOP_NUM] =
{
	D_RRH_ALMCD_DUM25,
	D_RRH_ALMCD_FWPLLBR2,
	D_RRH_ALMCD_FBPLLBR2,
	D_RRH_ALMCD_RXPLLBR2,
	D_RRH_ALMCD_RFIC1BR2,
	D_RRH_ALMCD_RFIC2BR2,
	D_RRH_ALMCD_FWJESDBR2,
	D_RRH_ALMCD_FBJESDBR2,
	D_RRH_ALMCD_RXJESDBR2,
	D_RRH_ALMCD_DUM26,
	D_RRH_ALMCD_TXGABR2,
	D_RRH_ALMCD_TOVEBR2,
	D_RRH_ALMCD_RXGABR2,
	D_RRH_ALMCD_TDDSW1BR2,
	D_RRH_ALMCD_TDDSW2BR2,
	D_RRH_ALMCD_TDDSW3BR2
};

/**	APD3 Alarm code define table */
USHORT	rcr_apd3almcode[RCD_APDALM_LOOP_NUM] =
{
	D_RRH_ALMCD_DUM27,
	D_RRH_ALMCD_FWPLLBR3,
	D_RRH_ALMCD_FBPLLBR3,
	D_RRH_ALMCD_RXPLLBR3,
	D_RRH_ALMCD_RFIC1BR3,
	D_RRH_ALMCD_RFIC2BR3,
	D_RRH_ALMCD_FWJESDBR3,
	D_RRH_ALMCD_FBJESDBR3,
	D_RRH_ALMCD_RXJESDBR3,
	D_RRH_ALMCD_DUM28,
	D_RRH_ALMCD_TXGABR3,
	D_RRH_ALMCD_TOVEBR3,
	D_RRH_ALMCD_RXGABR3,
	D_RRH_ALMCD_TDDSW1BR3,
	D_RRH_ALMCD_TDDSW2BR3,
	D_RRH_ALMCD_TDDSW3BR3
};

/* @} */

/****************************************************************************/
/*TDD-SRE RCT_CARDFB_DEVKIND_T							*/
/****************************************************************************/
/*!
 * @brief   card FB define table
 */
RCT_CARDFB_DEVKIND_T	rcr_cardFb_tdd_sre =
{
	RCD_TDD_FB_NUM,
	{RCD_FB_BPF_SWITCH,
	 RCD_FB_LNA,
	 RCD_FB_T_PA,
	 RCD_FB_TRX,
	 RCD_FB_TRX_INF,
	 RCD_FB_PORT_INF,
	 RCD_FB_MT_INF},
	RCD_CARDFB_BIT
};

/**
 * @brief   SFPコードチェック用テーブル.
 * @note    SFPのEEPROMから読み出したSFPコードと一致チェックするためのテーブル.
 */
const char *f_cpr_sfp[D_CPR_EEPROM_SFP_MAX] = {
	"CA46860-1094",		/* RE用Aタイプ */
	"CA46860-1095",		/* REC用Aタイプ */
	"CA46860-1096",		/* RE用Bタイプ */
	"CA46860-1097",		/* REC用Bタイプ */
	"CA46860-1348",		/* RE用Cタイプ */
	"CA46860-1349",		/* REC用Cタイプ */
	"CA46860-1350",		/* RE用Dタイプ */
	"CA46860-1351",		/* REC用Dタイプ */
	"CA46860-1386",		/* 9.8G/4.9G Slave用短距離タイプ */
	"CA46860-1385",		/* 9.8G/4.9G Master用短距離タイプ */
};

/**
 * @brief   SFPのタイプをチェックするためのテーブル.
 * @note    配列要素の内容は f_cpr_sfp の並びと合わせること.
 */
const int f_sfp_type[D_CPR_EEPROM_SFP_MAX] =
{
	0,
	-1,
	1,
	-1,
	2,
	-1,
	3,
	-1,
	2,
	-1,
};

/* @} */


