
/*
 * Copyright (c) 2008 - 2012, Andy Bierman, All Rights Reserved.
 * Copyright (c) 2012 - 2019, YumaWorks, Inc., All Rights Reserved.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *

*** Generated by yangdump-sdk 18.10-9

    User SIL-SA module
    module o-ran-delay-management
    revision 2019-02-04
    namespace urn:o-ran:delay:1.0
    organization O-RAN Alliance
    Created: 2019-06-21T02:49:13Z
    CLI parameters:
        format uc
        indent 4
        module o-ran-delay-management
        output u_o-ran-delay-management.c
        sil-get2
        sil-sa
        unified true

 */

#include <xmlstring.h>

#include "procdefs.h"
#include "agt.h"
#include "agt_action.h"
#include "agt_cb.h"
#include "agt_rpc.h"
#include "agt_sil_lib.h"
#include "agt_timer.h"
#include "agt_util.h"
#include "agt_val.h"
#include "cfg.h"
#include "dlq.h"
#include "getcb.h"
#include "ncx.h"
#include "ncx_feature.h"
#include "ncxmod.h"
#include "ncxtypes.h"
#include "obj.h"
#include "rpc.h"
#include "sil_sa.h"
#include "status.h"
#include "val.h"
#include "val_child.h"
#include "val_util.h"
#include "xml_val.h"
#include "u_o-ran-delay-management.h"
#include "y_o-ran-delay-management.h"

#include "i_o-ran-delay-management.h"


/* put your static variables here */

/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get
*
* Get database object callback for container ru-delay-profile
* Path: /delay-management/bandwidth-scs-delay-state/ru-delay-profile
* Fill in 'get2cb' response fields
*
* INPUTS:
*     see ncx/getcb.h for details (getcb_fn2_t)
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get (
    getcb_get2_t *get2cb,
    uint32 k_delay_management_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing)
{
    if (LOGINFO) {
        log_info("\nEnter %s:", __func__);
        log_info("\n    key_bw=%d, key_scs=%d", k_delay_management_bandwidth_scs_delay_state_bandwidth, k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing);
    }

    /* check the callback mode type */
    getcb_mode_t cbmode = GETCB_GET2_CBMODE(get2cb);
    switch (cbmode) {
    case GETCB_GET_VALUE:
        break;
    case GETCB_GETNEXT_VALUE:
        return ERR_NCX_NO_INSTANCE;
    default:
        return SET_ERROR(ERR_INTERNAL_VAL);
    }

    /* an NP container always exists so no test for node_exists
     * by the SIL or SIL-SA callback is needed */
    obj_template_t *obj = GETCB_GET2_OBJ(get2cb);
    status_t res = NO_ERR;

    /* optional: check if any content-match nodes are present */
    boolean match_test_done = FALSE;
    val_value_t *match_val = GETCB_GET2_FIRST_MATCH(get2cb);
    for (; match_val; match_val =
        GETCB_GET2_NEXT_MATCH(get2cb, match_val)) {

        /**** CHECK CONTENT NODES AGAINST THIS ENTRY ***/

    }
    GETCB_GET2_MATCH_TEST_DONE(get2cb) = match_test_done;

    /* go through all the requested terminal child objects */
    obj_template_t *childobj =
        getcb_first_requested_child(get2cb, obj);
    for (; childobj; childobj =
        getcb_next_requested_child(get2cb, childobj)) {

        const xmlChar *name = obj_get_name(childobj);
        xmlChar *para_temp;
        val_value_t *retval;

        /* Retrieve the value of this terminal node and 
         * add with getcb_add_return_val */

        if (!xml_strcmp(name, y_o_ran_delay_management_N_t2a_min_up)) {
            /* leaf t2a-min-up (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_t2a_min_up, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_t2a_min_up, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_t2a_min_up, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_t2a_min_up);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_t2a_max_up)) {
            /* leaf t2a-max-up (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_t2a_max_up, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_t2a_max_up, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_t2a_max_up, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_t2a_max_up);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_t2a_min_cp_dl)) {
            /* leaf t2a-min-cp-dl (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_t2a_min_cp_dl, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_t2a_min_cp_dl, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_t2a_min_cp_dl, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_t2a_min_cp_dl);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_t2a_max_cp_dl)) {
            /* leaf t2a-max-cp-dl (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_t2a_max_cp_dl, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_t2a_max_cp_dl, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_t2a_max_cp_dl, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_t2a_max_cp_dl);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_tcp_adv_dl)) {
            /* leaf tcp-adv-dl (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_tcp_adv_dl, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_tcp_adv_dl, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_tcp_adv_dl, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_tcp_adv_dl);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_ta3_min)) {
            /* leaf ta3-min (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_ta3_min, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_ta3_min, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_ta3_min, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_ta3_min);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_ta3_max)) {
            /* leaf ta3-max (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_ta3_max, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_ta3_max, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_ta3_max, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_ta3_max);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_t2a_min_cp_ul)) {
            /* leaf t2a-min-cp-ul (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_t2a_min_cp_ul, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_t2a_min_cp_ul, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_t2a_min_cp_ul, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_t2a_min_cp_ul);
                }
                return res;
            }
        } else if (!xml_strcmp(name, y_o_ran_delay_management_N_t2a_max_cp_ul)) {
            /* leaf t2a-max-cp-ul (uint32) */
            res = i_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get_para(
                k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                y_o_ran_delay_management_N_t2a_max_cp_ul, 
                &para_temp);
            if (LOGDEV1) {
                log_dev1("\n%s:%d %s bw = %d scs = %d res = %d", 
                    __func__, 
                    __LINE__, 
                    y_o_ran_delay_management_N_t2a_max_cp_ul, 
                    k_delay_management_bandwidth_scs_delay_state_bandwidth, 
                    k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing, 
                    res);
            }
            if(res == NO_ERR) {
                retval = agt_make_leaf2(obj, 
                    y_o_ran_delay_management_M_o_ran_delay_management, 
                    y_o_ran_delay_management_N_t2a_max_cp_ul, 
                    (const xmlChar *)para_temp, &res);
                if (retval) {
                    getcb_add_return_val(get2cb, retval);
                }
            }
            else {
                if(LOGWARN) {
                    log_warn("\n%s:%d operation failed to get param, para = %s", 
                        __func__, 
                        __LINE__, 
                        y_o_ran_delay_management_N_t2a_max_cp_ul);
                }
                return res;
            }
        }
    }

    return res;

} /* u_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_ru_delay_profile_get */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_edit
*
* Edit database object callback
* Path: /delay-management/bandwidth-scs-delay-state
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval; /* remove yumaworks warning */
    (void)curval; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
        log_info("\n    key_bw=%d, key_scs=%d", k_delay_management_bandwidth_scs_delay_state_bandwidth, k_delay_management_bandwidth_scs_delay_state_subcarrier_spacing);
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
        case OP_EDITOP_REPLACE:
        case OP_EDITOP_CREATE:
        case OP_EDITOP_DELETE:
            /* Edit NGのためError応答 */
            res = ERR_NCX_OPERATION_NOT_SUPPORTED;
            if(LOGWARN) {
                log_warn("\n%s: Operation not supported, editop=%s", __func__, op_editop_name(editop));
            }
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_bandwidth_scs_delay_state_edit */


#ifdef u_o_ran_delay_management_F_ADAPTIVE_RU_PROFILE

/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_t1a_max_up_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/bandwidth-scs-delay-state/o-du-delay-profile/t1a-max-up
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_t1a_max_up_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_t1a_max_up_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_tx_max_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/bandwidth-scs-delay-state/o-du-delay-profile/tx-max
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_tx_max_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_tx_max_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_ta4_max_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/bandwidth-scs-delay-state/o-du-delay-profile/ta4-max
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_ta4_max_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_ta4_max_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_rx_max_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/bandwidth-scs-delay-state/o-du-delay-profile/rx-max
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_rx_max_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_rx_max_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/bandwidth-scs-delay-state/o-du-delay-profile
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval; /* remove yumaworks warning */
    (void)curval; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_o_du_delay_profile_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/bandwidth-scs-delay-state
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*     k_ parameters are ancestor list key values.
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth,
    uint32 k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing)
{
    status_t res = NO_ERR;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval; /* remove yumaworks warning */
    (void)curval; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_bandwidth; /* remove yumaworks warning */
    (void)k_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_subcarrier_spacing; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_bandwidth_scs_delay_state_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t12_min_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/transport-delay/t12-min
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t12_min_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t12_min_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t34_min_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/transport-delay/t34-min
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t34_min_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t34_min_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t12_max_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/transport-delay/t12-max
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t12_max_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t12_max_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t34_max_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/transport-delay/t34-max
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t34_max_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;
    uint32 newval_val = (newval) ? VAL_UINT(newval) : 0;
    uint32 curval_val = (curval) ? VAL_UINT(curval) : 0;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval_val; /* remove yumaworks warning */
    (void)curval_val; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_t34_max_edit */


/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration/transport-delay
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval; /* remove yumaworks warning */
    (void)curval; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_transport_delay_edit */

/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_adaptive_delay_configuration_edit
*
* Edit database object callback
* Path: /delay-management/adaptive-delay-configuration
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_adaptive_delay_configuration_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval; /* remove yumaworks warning */
    (void)curval; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_adaptive_delay_configuration_edit */
#endif /* u_o_ran_delay_management_F_ADAPTIVE_RU_PROFILE */

/********************************************************************
* FUNCTION u_o_ran_delay_management_delay_management_edit
*
* Edit database object callback
* Path: /delay-management
* Add object instrumentation in COMMIT phase.
*
* INPUTS:
*     see agt/agt_cb.h for details
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_delay_management_edit (
    ses_cb_t *scb,
    rpc_msg_t *msg,
    agt_cbtyp_t cbtyp,
    op_editop_t editop,
    val_value_t *newval,
    val_value_t *curval)
{
    status_t res = NO_ERR;

    (void)scb; /* remove yumaworks warning */
    (void)msg; /* remove yumaworks warning */
    (void)newval; /* remove yumaworks warning */
    (void)curval; /* remove yumaworks warning */

    if (LOGINFO) {
        log_info("\nEnter %s: phase=%s, editop=%s", __func__, agt_cbtype_name(cbtyp), op_editop_name(editop));
    }

    switch (cbtyp) {
    case AGT_CB_VALIDATE:
        /* description-stmt validation here */
        break;
    case AGT_CB_APPLY:
        /* database manipulation done here */
        break;
    case AGT_CB_COMMIT:
        /* device instrumentation done here */
        switch (editop) {
        case OP_EDITOP_LOAD:
            break;
        case OP_EDITOP_MERGE:
            break;
        case OP_EDITOP_REPLACE:
            break;
        case OP_EDITOP_CREATE:
            break;
        case OP_EDITOP_DELETE:
            break;
        default:
            res = SET_ERROR(ERR_INTERNAL_VAL);
        }
        break;
    case AGT_CB_ROLLBACK:
        /* undo device instrumentation here */
        break;
    default:
        res = SET_ERROR(ERR_INTERNAL_VAL);
    }
    return res;

} /* u_o_ran_delay_management_delay_management_edit */

/********************************************************************
* FUNCTION u_o_ran_delay_management_init
*
* initialize the o-ran-delay-management server instrumentation library
*
* INPUTS:
*    modname == requested module name
*    revision == requested version (NULL for any)
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_init (
    const xmlChar *modname,
    const xmlChar *revision)
{
    status_t res = NO_ERR;
    ncx_module_t *o_ran_delay_management_mod = NULL;

    if (LOGINFO) {
        log_info("\nEnter %s:", __func__);
    }

    o_ran_delay_management_mod = ncx_find_module(modname, revision);
    if (o_ran_delay_management_mod == NULL) {
        return ERR_NCX_OPERATION_FAILED;
    }

    /* put your module initialization code here */
    
    return res;

} /* u_o_ran_delay_management_init */

/********************************************************************
* FUNCTION u_o_ran_delay_management_init2
*
* SIL init phase 2: non-config data structures
* Called after running config is loaded
*
* RETURNS:
*     error status
********************************************************************/
status_t u_o_ran_delay_management_init2 (void)
{
    status_t res = NO_ERR;

    /* put your init2 code here */
    if (LOGINFO) {
        log_info("\nEnter %s:", __func__);
    }

    return res;

} /* u_o_ran_delay_management_init2 */

/********************************************************************
* FUNCTION u_o_ran_delay_management_cleanup
*    cleanup the server instrumentation library
*
********************************************************************/
void u_o_ran_delay_management_cleanup (void)
{

    /* put your cleanup code here */
    if (LOGINFO) {
        log_info("\nEnter %s:", __func__);
    }

} /* u_o_ran_delay_management_cleanup */

/* END SIL-SA u_o_ran_delay_management.c */
