#------------------------------------------------------
# Makefile for APL process
#------------------------------------------------------
# Target: mnt server
#------------------------------------------------------
TARGET=rrh_mnt

include ../../../Makefile.in

#------------------------------------------------------
# parameter
#------------------------------------------------------
#CC=cc
#CC=/opt/ubq/devkit/arm/armv7/bin/arm-armv7-linux-gnueabi-gcc
OPT+= $(CFLAGS)

#------------------------------------------------------
# build top
#------------------------------------------------------
TOP=../../../..

#------------------------------------------------------
# Library
#------------------------------------------------------
LIBS=-lm -ldl -lrt -lpthread \
	-lbpf_com -lbpf_devc -lbpf_facc \
	-lbpf_mblm -lbpf_string -lbpf_hrtm -lbpf_svrm -lbpf_itcm -lbpf_ipcm -lbpf_log -lbpf_plog \
	-lrrhapi_l2 -lrrhapi_com -lrrhapi_cpri -lrrhapi_fmng -lrrhapi_svp

CMN_LIBDIR=$(TOP)/src/cmn/lib
CMN_LIBS = -L$(CMN_LIBDIR) -lcmu_recv -lcmu_send -lcmn_dbg -lbpf_mblm

#------------------------------------------------------
# Default Parameters
#------------------------------------------------------
LIBDIR=$(TOP)/ramdisk/target/lib
OBJDIR=$../obj/

#------------------------------------------------------
# PF Includes
#------------------------------------------------------
INCLUDES=\
	-I$(TOP)/src/sys/inc \
	-I$(TOP)/src/cmn/dcm/inc \
	-I$(TOP)/src/sys/inc_mw \
	-I$(TOP)/src/sys/inc_arch \
	-I$(TOP)/src/api/inc \
	-I$(TOP)/src/cmn/com/inc \
	-I$(TOP)/src/cmn/cmu/inc \
	-I$(TOP)/src/cmn/debug/inc \
	-I$(TOP)/src/pf/pf_fhm/sys \
	-I../mkm/inc \
	-I../lnr/inc \
	-I../lns/inc \
	-I../main/inc \
	-I../inc

#------------------------------------------------------
# Source Files
#------------------------------------------------------
SRC=\
	$(TOP)/src/cmn/dcm/src/tm_cm_Breq.c \
	$(TOP)/src/cmn/dcm/src/m_cm_Delay.c \
	$(TOP)/src/cmn/dcm/src/tm_cm_Assert.c \
	$(TOP)/src/cmn/dcm/src/tm_cm_MWait.c \
	$(TOP)/src/cmn/dcm/src/tm_cm_MemPadc.c \
	$(TOP)/src/cmn/dcm/src/tm_cm_MAbort.c \
	$(TOP)/src/cmn/dcm/src/m_cm_chksig.c \
	$(TOP)/src/cmn/dcm/src/m_cm_L3MsgSend.c \
	$(TOP)/src/cmn/dcm/src/m_cm_ActiveChk.c \
	$(TOP)/src/cmn/dcm/src/m_cm_ErrCntRegSet.c \
	$(TOP)/src/cmn/com/src/f_com_aplCom.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_rom.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_log.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_abort.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_shm.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_conn_disk.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_assert.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_fhm_state.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_cardst_s3g.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_cardst_3g.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_rest_s3g.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_re_port_sta_s3g.c \
	$(TOP)/src/cmn/com/src/f_cmn_com_fw_info_re.c \
	../mkm/src/m_mk_abort.c \
	../mkm/src/m_mk_anlz.c \
	../mkm/src/m_mk_REMTOperation.c \
	../mkm/src/m_mk_FHMMTOperation.c \
	../mkm/src/m_mk_cardStat_ChgNfy.c \
	../mkm/src/m_mk_cm_DLEnd.c \
	../mkm/src/m_mk_cm_mondatproc.c \
	../mkm/src/m_mk_cm_setsndmsg.c \
	../mkm/src/m_mk_cprimon_datarcv.c \
	../mkm/src/m_mk_cprimon_datasnd.c \
	../mkm/src/m_mk_cprimon_stpreq.c \
	../mkm/src/m_mk_cprimon_strreq.c \
	../mkm/src/m_mk_cprimsg_datarcv.c \
	../mkm/src/m_mk_cprisimu_datarcv.c \
	../mkm/src/m_mk_cprisimu_datasnd.c \
	../mkm/src/m_mk_cprisimu_stpreq.c \
	../mkm/src/m_mk_cprisimu_strreq.c \
	../mkm/src/m_mk_DataEndNtcRcv.c \
	../mkm/src/m_mk_DataEndNtcRsp.c \
	../mkm/src/m_mk_FileDataRcv.c \
	../mkm/src/m_mk_FileDlStrReq.c \
	../mkm/src/m_mk_FileDlStrRsp.c \
	../mkm/src/m_mk_FileWaitTimTO.c \
	../mkm/src/m_mk_FileWtRsp.c \
	../mkm/src/m_mk_HB.c \
	../mkm/src/m_mk_init.c \
	../mkm/src/m_mk_l1linkstat_chgnfy.c \
	../mkm/src/m_mk_l2linkstat_chgnfy.c \
	../mkm/src/m_mk_l3linkstat_chgnfy.c \
	../mkm/src/m_mk_main.c \
	../mkm/src/m_mk_MonDatTO.c \
	../mkm/src/m_mk_nop.c \
	../mkm/src/m_mk_ram.c \
	../mkm/src/m_mk_REMTConn.c \
	../mkm/src/m_mk_REMTRelease.c \
	../mkm/src/m_mk_RENgcodeTrans.c \
	../mkm/src/m_mk_rom.c \
	../mkm/src/m_mk_subCardstatus.c \
	../mkm/src/m_mk_subl2state.c \
	../mkm/src/m_mk_tcpdata_rcv.c \
	../mkm/src/m_mk_tcpdata_sndrsp.c \
	../mkm/src/m_mk_tcpinit_rsp.c \
	../mkm/src/m_mk_tcplink_conn.c \
	../mkm/src/m_mk_tcplink_rel.c \
	../mkm/src/m_mk_TcpServInitReq.c \
	../mkm/src/m_mk_TRAFLWRTTO.c \
	../mkm/src/m_mk_TServQuitNtc.c \
	../mkm/src/m_mk_SysParaChgNtc.c \
	../lnr/src/tm_lr_abort.c \
	../lnr/src/tm_lr_anlz.c \
	../lnr/src/tm_lr_init.c \
	../lnr/src/tm_lr_main.c \
	../lnr/src/tm_lr_nop.c \
	../lnr/src/tm_lr_ram.c \
	../lnr/src/tm_lr_rom.c \
	../lnr/src/tm_lr_tcpinit.c \
	../lnr/src/tm_lr_tcpstr.c \
	../lns/src/tm_ls_abort.c \
	../lns/src/tm_ls_anlz.c \
	../lns/src/tm_ls_init.c \
	../lns/src/tm_ls_main.c \
	../lns/src/tm_ls_nop.c \
	../lns/src/tm_ls_ram.c \
	../lns/src/tm_ls_rom.c \
	../lns/src/tm_ls_tcprel.c \
	../lns/src/tm_ls_tcpsnd.c \
	../main/src/mnt_main_main.c \
	../main/src/mnt_main_ram.c \
	../main/src/mnt_main_rom.c \
	../main/src/mnt_main_systemInit.c \
	../main/src/mnt_thrd_main.c \
	../com/src/mnt_com_rom.c \
	../com/src/mnt_com_ram.c \
	../com/src/mnt_com_endian_util.c \
	../com/src/mnt_com_function.c


OBJS=$(SRC:.c=.o)
#------------------------------------------------------
# rules
#------------------------------------------------------
all: $(TARGET)
$(TARGET): $(OBJS)
	$(CC) $(OPT) $(LDFLAGS) -o $(TARGET) $(OBJS) -L$(LIBDIR) $(LIBS) $(CMN_LIBS) -lrrhapi_com
%.o: %.c
	$(CC) $(OPT) -c  $< $(INCLUDES) -o $@
#	$(CC) -c $(cflag) $< -o $@ -L$(LIBDIR)
clean:
	rm -rf ../mkm/src/*.o ../mkm/src/*.d
	rm -rf ../lnr/src/*.o ../lnr/src/*.d
	rm -rf ../lns/src/*.o ../lns/src/*.d
	rm -rf ../main/src/*.o ../main/src/*.d
	rm -rf ../com/src/*.o ../com/src/*.d
	rm -rf ../dbg/src/*.o ../dbg/src/*.d
