all: alllib 
clean: allclean

alllib:
	#o-ran_all
	cd o-ran_all;make
	#o-ran-delay-management
	cd o-ran-delay-management;make
	#o-ran-file-management
	cd o-ran-file-management;make
	#o-ran-troubleshooting
	cd o-ran-troubleshooting;make
	#o-ran-externalio
	cd o-ran-externalio;make
	#o-ran-fan
	cd o-ran-fan;make

allclean:
	#o-ran_all
	cd o-ran_all;make clean
	#o-ran-delay-management
	cd o-ran-delay-management;make clean
	#o-ran-file-management
	cd o-ran-file-management;make clean
	#o-ran-troubleshooting
	cd o-ran-troubleshooting;make clean
	#o-ran-externalio
	cd o-ran-externalio;make clean
	#o-ran-fan
	cd o-ran-fan;make clean

