/*!
 * @skip  $ld:$
 * @file  mnt_main_rom.c
 * @brief ROM table
 * @date  2013/11/07 FFCS)zhaodx create for zynq\n
 * @date  2015/07/30 TDIPS)maruyama  不要スレッドの削除
 * All Rights Reserved, Copyright (C) FUJITSU LIMITED 2013
 */
 
/*!
 * @addtogroup RRH_MNT_MAIN
 * @{
 */
#include "m_cm_header.h" 
#include "mnt_com_inc.h"
#include "mnt_main_def.h"
#include "mnt_main_ftyp.h"
#include "f_com_aplCom.h"
#include "f_cmn_cmu_inc.h"
#include "rrhApi_L2.h"
#include "rrhApi_Dbg.h"
#include "rrhApi_Svp.h"
#include "rrhApi_Cpri.h"

/****************************************************************************/
/* proc thread function matrix                                                 */
/****************************************************************************/
extern VOID mnt_mkm_main(VOID*);
extern VOID mnt_lnr_main(VOID*);
extern VOID mnt_lns_main(VOID*);
extern VOID mnt_rcv_main(VOID*);
extern VOID mnt_snd_main(VOID*);
extern VOID mnt_dbg_main(VOID*);
			
			
/*!
 * @brief   スレッド管理テーブル
 * @date    2015/07/30 TDIPS) maruyama modify 不要スレッドの削除(mtm, mlr, mls)
 */
const T_SYS_THRDINFO mnt_comr_ThrMngTbl[D_RRH_THDID_MT_MAX] = 
{
	/* msgQ*/			/*name*/	/*Priority*/	/*stack size*/	/*Entry*/	/*need create*/	/*msgQID*/
	{CMD_TSKID_INI,		"mnt_main",	D_MNT_PRIORITY_MAIN,	D_MNT_STACKSIZE_MAIN,	D_RRH_NULL,		D_RRH_ON},
	{CMD_TSKID_MKM,		"mnt_mkm",	D_MNT_PRIORITY_MKM,		D_MNT_STACKSIZE_MKM,	mnt_mkm_main,	D_RRH_ON},
	{CMD_TSKID_LNR,		"mnt_lnr",	D_MNT_PRIORITY_LNR,		D_MNT_STACKSIZE_LNR,	mnt_lnr_main,	D_RRH_ON},
	{CMD_TSKID_LNS,		"mnt_lns",	D_MNT_PRIORITY_LNS,		D_MNT_STACKSIZE_LNS,	mnt_lns_main,	D_RRH_ON},
	{CMD_TSKID_SND,		"mnt_send",	D_MNT_PRIORITY_SEND,	D_MNT_STACKSIZE_SEND,	mnt_snd_main,	D_RRH_ON},
	{CMD_TSKID_RCV,		"mnt_recv",	D_MNT_PRIORITY_RECV,	D_MNT_STACKSIZE_RECV,	mnt_rcv_main,	D_RRH_ON},
	{CMD_TSKID_DBG,		"mnt_dbg",	D_MNT_PRIORITY_DBG,		D_MNT_STACKSIZE_DBG,	mnt_dbg_main,	D_RRH_OFF}
};

/* CMU recv paramater thread create manage table */
T_CMU_CREATE_THREAD	mnt_mainr_cmusRecvThdCreMng	= 
{												
	{
		/* EventID */							/* SignalKind */	/* 送信先QID */	/* dummy */
		{ D_SYS_MSGID_ALLTSKININTC,				0x00000000,				CMD_TSKID_INI,  0x00000000 },
		{ D_API_MSGID_DBG_CPRIMON_DATA_RCV_NTC,	0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ D_API_MSGID_DBG_CPRIMON_DATA_SND_NTC,	0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ D_API_MSGID_CPRI_STATE_STATE_NTC, 	0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ D_API_MSGID_L2_LINKSTATE_NTC, 		0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ CMD_TSKIF_L3STANTC, 					0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ CMD_TSKIF_L1MONDATSNDNTC, 			0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ CMD_TSKIF_L1MONDATRCVNTC, 			0x00000000,				CMD_TSKID_MKM,	0x00000000 },
		{ CMD_TSKIF_SYSPARA_CHG_NTC, 			0x00000000, 			CMD_TSKID_MKM,	0x00000000 },
#ifndef OPT_RRH_ZYNQ_REC
		{ D_API_MSGID_DBG_RECV_SIMUCPRIMSG,		0x00000000,				CMD_TSKID_MKM,	0x00000000 },
#else
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_HCRES, 	CMD_TSKID_MKM ,	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_LINKSTSRES, 	CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FIRMFILERES, 	CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FILEINFRES, CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FILEDATSND, CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FILSNDFINRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_UFIRMFILERES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_UFILEINFRES,	CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_UFILEDATSND,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_UFILSNDFINRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_TRXSETRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_TRXRELRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_TOFFSETINFRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_CARONOFFRES,	CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_EQPSTRRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_SLOTINFRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_RESTSRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_CARDINFRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_REVERRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_RECARDCNTRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_CARDSTSRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_CARLSTSRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_REPORTCNTRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_REPORTSTSRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_RECRDDIARES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_REOBSLOGRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_REOBLOGSTPRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_EXTDATSNDRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_EXTDATRCVREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_MTADDSETRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLDMTCNCREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLDCOMSNDRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLDCOMRCVREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLDFILSNDRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLDFILRCVREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLMTCNCRELREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FLMTCMPRELRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_SVMTCNTRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_SVMTDATSNDRES,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_SVMTDATRCVREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_SVMTCNTRELREQ,CMD_TSKID_MKM, 	0x00000000 },
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_SVMTFORRELRES,CMD_TSKID_MKM, 	0x00000000 },	
		{ D_API_MSGID_L2_CPRIMSG_RCV_NTC,		CMD_CPRID_FTPPORTSETRES,CMD_TSKID_MKM, 	0x00000000 },
#endif
		{ 0x00000000	,	0x00000000	,	0x00000000	,	0x00000000		},
		{ 0x00000000	,	0x00000000	,	0x00000000	,	0x00000000		}
	},
	D_RRH_PROCID_MT,								/* プロセスID */
	D_RRH_PROCQUE_MT,								/* プロセスQID */
	D_RRH_THDID_MT_RECV,							/* Thread-ID */
	CMD_TSKID_RCV,									/* Thread-QID */
	CMD_TSKID_INI,									/* 起動元 Thrad-QID */
	E_RRH_CMU_RECV_ID,								/* スレッド情報(0:recv, 1:send) */
	"mnt_recv"										/* スレッド名	 */
};

/* @} */
