/**
 *  @skip	$Id:$
 *  @file
 *  @brief	RAM Table
 *  @note	NOTE THAT YOU MUST NOT EDIT THIS FILE MANUALLY, which is automatically generated with VBA macro. \n
 * 			See also TableSpecifications(dpda)_ram.xls
 * 
 *  ALL Rights Reserved, Copyright (c) FUJITSU Limited 2011-2015
 */
/******************************************************************************************************************************/

#include	"f_dpda_inc.h"

/** @addtogroup RRH_PF_RFP
 *  @{
 */
T_DPDA_REGDATA				f_dpdaw_regdataReal __attribute__ ((aligned (32)));			/**< register data table						*/
T_DPDA_EXTDATA				f_dpdaw_extdataReal __attribute__ ((aligned (32)));
T_DPDA_STATUS_INFO			f_dpdaw_statusInfo __attribute__ ((aligned (32)));			/**< status information テーブル				*/
T_DPDA_EXT_STATUS_INFO		f_dpdaw_statusInfoExt __attribute__ ((aligned (32)));		/**< status information テーブル (拡張領域)		*/

UINT						f_dpdaw_almThreshold[E_DPDA_ALM_THRESH_NUM_MAX][D_DPDA_ANTMAX];		/**< alm threshold table				*/
UINT						f_dpdaw_occurAlmInstanceId[D_DPDA_ALM_NUM];					/**< 発生アラームInstanceIDリスト				*/
UINT						f_dpdaw_clearAlmInstanceId[D_DPDA_ALM_NUM];					/**< 回復アラームInstanceIDリスト				*/
T_DPDA_ALM_STATE			f_dpdaw_almState[D_DPDA_ALM_NUM];							/**< dpda alarm state table				*/
UINT						f_dpdaw_almCollectInfo[E_DPDA_ALM_COLLECT_INFO_NUM];		/**< dpda alarm collect sw modify info table	*/
T_DPDA_ALM_INFO				*f_dpdaw_almInfo;											/**< dpda alarm information table				*/

T_DPDA_INFO_ALL				*f_dpdaw_info_all;											/**< DPDAデバッグ用情報ログtable				*/

UINT						f_dpdaw_exeCltCalib_flg;									/**< くクレメンテキャリブレーション実行フラグ	*/

UINT						f_dpdaw_regTxGainData[D_DPDA_ANTMAX][D_DPDA_CARMAX];		/**< TXゲイン設定値								*/
UINT						f_dpdaw_regRxGainData[D_DPDA_ANTMAX][D_DPDA_CARMAX];		/**< RXゲイン設定値								*/

T_DPDA_IMPULSE_COEFFICIENT	f_dpdaw_calcImpulseCoefficient[D_DPDA_IMPULSE_NUM];			/**< インパルス係数(Car1,NCO is not0)格納領域	*/

T_DPDA_ALM_LOG_DEBUG		*f_dpdaw_almLog;											/**< アラーム発生時解析用ログtable				*/
T_RRH_ALM_LOG_FOR_HIST		*f_dpdaw_almLogForHistory;									/**< アラームヒストリー用ログ情報格納位置		*/
T_RRH_LOG_TEMP				*f_dpdaw_tempLog;											/**< 温度ログ情報格納位置						*/
T_DPDA_ANTCARSTATEINFO		f_dpdaw_antCarStateInfo __attribute__ ((aligned (32)));		/**< ant/carrier state info table				*/
T_DPDA_LOG_CAR_STATE		*f_dpdaw_carStateLog;										/**< キャリア状態ログ							*/


UINT						*f_dpdaw_spiCpldAddr;										/**< SPI CPLD用レジスタアドレステーブル			*/
UINT						*f_dpdaw_spiTxAddr;											/**< SPI Tx系レジスタアドレステーブル			*/
UINT						*f_dpdaw_spiRxAddr;											/**< SPI Rx系レジスタアドレステーブル			*/
 	
UINT						f_dpdaw_ant_max_num;										/**< 装置種別によるアンテナ数(max)				*/
UINT						f_dpdaw_ant_unit_max_num;									/**< 装置種別によるユニット数(max)				*/
UINT						f_dpdaw_carrier_max_num;									/**< 装置種別によるキャリア数(max)				*/

UINT						f_dpdaw_reKind;												/**< 装置種別(0:sub6 1:mmW						*/
UINT						f_dpdaw_ruIndex;											/**< RU Index(0:sub6 3.7G, 1:sub6 4.5G, 2:mmW 280G	*/

UINT						f_dpdaw_teston_flag = 0;									/**< testtxon/offフラグ(bit毎のフラグ 0:OFF, 1:ON	*/
																						/**< mmw[31:16]										*/
																						/**< Ant   :              B               A			*/
																						/**< Cr    :7 6 5 4 3 2 1 0 7 6 5 4 3 2 1 0			*/
																						/**< bit列 :0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0			*/
																						/**< sub6[0:15]										*/
																						/**< Ant   :  H   G   F   E   D   C   B   A			*/
																						/**< Cr    :1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0			*/
																						/**< bit列 :0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0			*/


UINT						f_dpdaw_index_TssiPos = 0;
UINT						f_dpdaw_index_AntPowPos = 0;
UINT						f_dpdaw_index_RefPowPos = 0;
UINT						f_dpdaw_index_RefPowPos_VSWR = 0;
UINT						f_dpdaw_index_FbPowPos = 0;
UINT						f_dpdaw_index_VswrPos = 0;
UINT						f_dpdaw_index_RxPowPos = 0;
UINT						f_dpdaw_index_RtwpPos = 0;
UINT						f_dpdaw_index_CarrierPos = 0;
UINT						f_dpdaw_index_AntDisPos = 0;
UINT						f_dpdaw_index_A000_0200 = 0;
UINT						f_dpdaw_index_A000_0210 = 0;
UINT						f_dpdaw_index_A000_0B10= 0;
UINT						f_dpdaw_index_A000_0B20= 0;
UINT						f_dpdaw_index_A000_0B30= 0;
UINT						f_dpdaw_index_B000_0B10= 0;
UINT						f_dpdaw_index_B000_0B20= 0;
UINT						f_dpdaw_index_B000_02C0= 0;
UINT						f_dpdaw_index_B000_0200= 0;
UINT						f_dpdaw_index_B000_0210= 0;
UINT						f_dpdaw_index_SvBusPos = 0;
UINT						f_dpdaw_index_B100_0040= 0;
UINT						f_dpdaw_index_B100_0044= 0;
UINT						f_dpdaw_index_B100_0048= 0;
UINT						f_dpdaw_index_B100_004C= 0;
UINT						f_dpdaw_index_A200_0720= 0;

UINT						f_dpdaw_rficSetupCmp = 0;

UINT						f_dpdaw_index_A201_43C8= 0;

UINT						f_dpdaw_index_B100_0050= 0;
UINT						f_dpdaw_index_B100_0054= 0;
UINT						f_dpdaw_index_B100_0058= 0;
UINT						f_dpdaw_index_B100_005C= 0;

T_RRH_TXPOW_DETECT_TBL*		f_dpdaw_txpow_detect;
T_RRH_TXPOW_DETECT_LOG*		f_dpdaw_txpow_log;
T_RRH_LUT_LOG*				f_dpdaw_lut_log;
T_RRH_LOG_UPSIGSTOP_HIS*	f_dpdaw_upsigstop_log;
T_RRH_LOG_CAL_HIS*			f_dpdaw_cal_log;
struct timespec				f_dpdaw_sfnload_settime;

 
T_RRH_LOG_DLF_HIS*			f_dpdaw_dlf_log;

/*!
 * @name ALM
 * @note ALM
 * @{
 */
T_DPDA_ALM_REPORT f_dpdar_alarm_report_tbl[E_DPDA_ALM_SUB6_NUM_MAX] =
{
	/*		ope_fid				,		fltid						,	almlog	 ,	almmsk		*/
	{	E_DU_SVCTL_OPE_FID04_ALM,	D_DU_FLTID_JC_PLL_UNLOCK,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_JCPLL_UNLOCK_ALM	*/
	{	E_DU_SVCTL_OPE_FID06_ALM,	D_DU_FLTID_PS_ALM,					D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_PS_ALM			*/
	{	E_DU_SVCTL_OPE_FID06_ALM,	D_DU_FLTID_POW_ERR1,				D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_POW_ERR1		*/
	{	E_DU_SVCTL_OPE_FID06_ALM,	D_DU_FLTID_POW_ERR2,				D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_POW_ERR2		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SYS_PLL_UNLOCK_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_SYS_PLL_UNLOCK_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_IC_PLL_UNLOCK_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_IC_PLL_UNLOCK_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_ETH_PLL_UNLOCK_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_ETH_PLL_UNLOCK_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_PCIE_ERR1_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_PCIE_ERR1_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_PCIE_ERR2_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_PCIE_ERR2_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_SV_FAIL_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_SV_FAIL_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_ETH_ALM,					D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_ETHER_ALM		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SRAM_CORRECT_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_SRAM_CON_ERR		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SRAM_UNCORRECT_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_SRAM_UNCON_ERR		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_IC_TX_ERR_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_IC_TX_ERR_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_IC_RX_ERR_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_IC_RX_ERR_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LLB_IC_TX_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_IC_TX_ERR_TRX	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LLB_IC_RX_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_IC_RX_ERR_TRX	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_AUTO_CRUISE_HC_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_AUTO_CR_HC_ERR	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SYS_PLL_UNLOCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_SYS_PLL_UNLOCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_IC_PLL_UNLOCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_IC_PLL_UNLOCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYICPLLULCK1_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_PHYICPLLULCK1_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYICPLLULCK2_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_PHYICPLLULCK2_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHY_POW_ALM_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_PHYPOWALM_TRX1		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYJS1PLLULCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_PHYJS1PLLULCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYJS2PLLULCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_PHYJS2PLLULCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_SV_FAIL_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TRX1_SV_FAIL_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R1_TX_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_R1_TX_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R1_FB_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_R1_FB_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R1_RX_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_R1_RX_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R2_TX_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_R2_TX_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R2_FB_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_R2_FB_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R2_RX_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_R2_RX_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LMB_CORRECT_ERR,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_LMB_COR_ERR			*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LMB_UNCORRECT_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_LMB_UNCOR_ERR		*/
	{	E_DU_SVCTL_OPE_FID08_ALM,	D_DU_FLTID_RFIC1_ALM,				D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_SUB6_RFIC1_ALM			*/
	{	E_DU_SVCTL_OPE_FID08_ALM,	D_DU_FLTID_RFIC2_ALM,				D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_SUB6_RFIC2_ALM			*/
	{	E_DU_SVCTL_OPE_FID10_ALM_A,	D_DU_FLTID_TX_GAIN_ALM_ANT_A,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TX_GAIN_ALM_ANT_A	*/
	{	E_DU_SVCTL_OPE_FID10_ALM_B,	D_DU_FLTID_TX_GAIN_ALM_ANT_B,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TX_GAIN_ALM_ANT_B	*/
	{	E_DU_SVCTL_OPE_FID10_ALM_C,	D_DU_FLTID_TX_GAIN_ALM_ANT_C,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TX_GAIN_ALM_ANT_C	*/
	{	E_DU_SVCTL_OPE_FID10_ALM_D,	D_DU_FLTID_TX_GAIN_ALM_ANT_D,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TX_GAIN_ALM_ANT_D	*/
	{	E_DU_SVCTL_OPE_FID10_ALM_A,	D_DU_FLTID_TOVER_ALM_ANT_A,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TOVER_ALM_ANT_A		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_B,	D_DU_FLTID_TOVER_ALM_ANT_B,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TOVER_ALM_ANT_B		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_C,	D_DU_FLTID_TOVER_ALM_ANT_C,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TOVER_ALM_ANT_C		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_D,	D_DU_FLTID_TOVER_ALM_ANT_D,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TOVER_ALM_ANT_D		*/
	{	E_DU_SVCTL_OPE_FID11_ALM_A,	D_DU_FLTID_RX_GAIN_ALM_ANT_A,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_RX_GAIN_ALM_ANT_A	*/
	{	E_DU_SVCTL_OPE_FID11_ALM_B,	D_DU_FLTID_RX_GAIN_ALM_ANT_B,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_RX_GAIN_ALM_ANT_B	*/
	{	E_DU_SVCTL_OPE_FID11_ALM_C,	D_DU_FLTID_RX_GAIN_ALM_ANT_C,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_RX_GAIN_ALM_ANT_C	*/
	{	E_DU_SVCTL_OPE_FID11_ALM_D,	D_DU_FLTID_RX_GAIN_ALM_ANT_D,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_RX_GAIN_ALM_ANT_D	*/
	{	E_DU_SVCTL_OPE_FID12_ALM_A,	D_DU_FLTID_VSWR_ALM_ANT_A,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_VSWR_ALM_ANT_A	*/
	{	E_DU_SVCTL_OPE_FID12_ALM_B,	D_DU_FLTID_VSWR_ALM_ANT_B,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_VSWR_ALM_ANT_B	*/
	{	E_DU_SVCTL_OPE_FID12_ALM_C,	D_DU_FLTID_VSWR_ALM_ANT_C,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_VSWR_ALM_ANT_C	*/
	{	E_DU_SVCTL_OPE_FID12_ALM_D,	D_DU_FLTID_VSWR_ALM_ANT_D,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_VSWR_ALM_ANT_D	*/
	{	E_DU_SVCTL_OPE_FID31_ALM,	D_DU_FLTID_TEMP_ALM_HIGH,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TEMP_ALM_HIGH		*/
	{	E_DU_SVCTL_OPE_FID30_ALM,	D_DU_FLTID_TEMP_ALM_LOW,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_SUB6_TEMP_ALM_LOW		*/
};


/*!
 * @name ALM
 * @note ALM
 * @{
 */
T_DPDA_ALM_REPORT f_dpdar_alarm_report_tbl_mmw[E_DPDA_ALM_MMW_NUM_MAX] =
{
	/*		ope_fid				,		fltid						,	almlog	 ,	almmsk		*/
	{	E_DU_SVCTL_OPE_FID04_ALM,	D_DU_FLTID_JC_PLL_UNLOCK,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_JCPLL_UNLOCK_ALM		*/
	{	E_DU_SVCTL_OPE_FID04_ALM,	D_DU_FLTID_RF_PLL_UNLOCK,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_RFPLL_UNLOCK_ALM		*/
	{	E_DU_SVCTL_OPE_FID06_ALM,	D_DU_FLTID_PS_ALM,					D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_PS_ALM				*/
	{	E_DU_SVCTL_OPE_FID06_ALM,	D_DU_FLTID_POW_ERR1,				D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_POW_ERR1				*/
	{	E_DU_SVCTL_OPE_FID06_ALM,	D_DU_FLTID_POW_ERR2,				D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_POW_ERR2				*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SYS_PLL_UNLOCK_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_SYS_PLL_UNLOCK_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_IC_PLL_UNLOCK_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_IC_PLL_UNLOCK_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_ETH_PLL_UNLOCK_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_ETH_PLL_UNLOCK_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_PCIE_ERR1_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_PCIE_ERR1_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_PCIE_ERR2_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_PCIE_ERR2_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_SV_FAIL_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_SV_FAIL_LLB		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_ETH_ALM,					D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_ETHER_ALM			*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SRAM_CORRECT_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_SRAM_CON_ERR			*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SRAM_UNCORRECT_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_SRAM_UNCON_ERR		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_IC_TX_ERR_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_IC_TX_ERR_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_IC_RX_ERR_LLB,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_IC_RX_ERR_LLB	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LLB_IC_TX_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_IC_TX_ERR_TRX	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LLB_IC_RX_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_IC_RX_ERR_TRX	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_SYS_PLL_UNLOCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_SYS_PLL_UNLOCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_IC_PLL_UNLOCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_IC_PLL_UNLOCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYICPLLULCK1_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_PHYICPLLULCK1_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYICPLLULCK2_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_PHYICPLLULCK2_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHY_POW_ALM_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_PHYPOWALM_TRX1		*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_PHYJS1PLLULCK_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_PHYJS1PLLULCK_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_TRX1_SV_FAIL_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TRX1_SV_FAIL_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R1_TX_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_R1_TX_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_R1_RX_JESD_ERR_TRX1,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_R1_RX_JESD_ERR_TRX1	*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LMB_CORRECT_ERR,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_LMB_COR_ERR			*/
	{	E_DU_SVCTL_OPE_FID07_ALM,	D_DU_FLTID_LMB_UNCORRECT_ERR,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_LMB_UNCOR_ERR		*/
	{	E_DU_SVCTL_OPE_FID08_ALM,	D_DU_FLTID_TXDAC_ALM,				D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TXDAC_ALM			*/
	{	E_DU_SVCTL_OPE_FID08_ALM,	D_DU_FLTID_RXDAC_ALM,				D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_RXDAC_ALM			*/
	{	E_DU_SVCTL_OPE_FID10_ALM_A,	D_DU_FLTID_TOVER_ALM_ANT_A,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TOVER_ALM_ANT_A		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_B,	D_DU_FLTID_TOVER_ALM_ANT_B,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TOVER_ALM_ANT_B		*/
	{	E_DU_SVCTL_OPE_FID11_ALM_A,	D_DU_FLTID_RX_GAIN_ALM_ANT_A,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_RX_GAIN_ALM_ANT_A	*/
	{	E_DU_SVCTL_OPE_FID11_ALM_B,	D_DU_FLTID_RX_GAIN_ALM_ANT_B,		D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_RX_GAIN_ALM_ANT_B	*/
	{	E_DU_SVCTL_OPE_FID31_ALM,	D_DU_FLTID_TEMP_ALM_HIGH,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TEMP_ALM_HIGH		*/
	{	E_DU_SVCTL_OPE_FID30_ALM,	D_DU_FLTID_TEMP_ALM_LOW,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TEMP_ALM_LOW			*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V1,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V01		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V2,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V02		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V3,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V03		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V4,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V04		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V5,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V05		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V6,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V06		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V7,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V07		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V8,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V08		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V9,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V09		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V10,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V10		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V11,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V11		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V12,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V12		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V13,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V13		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V14,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V14		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V15,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V15		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_V16,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_V16		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H1,			D_SYS_OFF,	D_SYS_OFF	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H01		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H2,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H02		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H3,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H03		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H4,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H04		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H5,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H05		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H6,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H06		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H7,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H07		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H8,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H08		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H9,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H09		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H10,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H10		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H11,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H11		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H12,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H12		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H13,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H13		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H14,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H14		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H15,			D_SYS_OFF,	D_SYS_ON	},		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H15		*/
	{	E_DU_SVCTL_OPE_FID10_ALM_VH,D_DU_FLTID_TX_PW_ALM_H16,			D_SYS_OFF,	D_SYS_ON	}		/*	E_DPDA_ALM_MMW_TX_PWR_ALM_H16		*/
};


/** @} */
