/*!
 * @skip  $ld:$
 * @file  l3_com_rom.c
 * @brief ROM table(com)
 * @date  2013/11/20 FFCS)linb Create\n
 * All Rights Reserved, Copyright (C) FUJITSU LIMITED 2013
 */
 
/*!
 * @addtogroup RRH_L3_COM
 * @{
 */
#include "m_cm_header.h"
#include "l3_com_inc.h"

/**
 * @brief subscription of cpri message notice用のテーブル
 * @date  2015/09/27 TDI)satou CMD_CPRID_FTPPORTSETREQを追加
 */
UINT const l3_comr_cprimsg_subTbl[D_L3_CPRIMSGNUM] =
{
        CMD_CPRID_CARDSTSREQ,
        CMD_CPRID_CARLSTSREQ,
        CMD_CPRID_HCREQ,
        CMD_CPRID_REPORTSTSREQ,
        CMD_CPRID_RESTSREQ,
        CMD_CPRID_TOFFSETINFREQ,
        CMD_CPRID_EQPSTRREQ,
        CMD_CPRID_FILEDATSND,
        CMD_CPRID_FILSNDFINNTC,
        CMD_CPRID_FIRMFILEREQ,
        CMD_CPRID_FILEINFREQ,
        CMD_CPRID_UFILEDATSND,
        CMD_CPRID_UFILSNDFINNTC,
        CMD_CPRID_UFIRMFILEREQ,
        CMD_CPRID_UFILEINFREQ,
        CMD_CPRID_RETIMSETREQ,
        CMD_CPRID_LINKSTSREQ,
        CMD_CPRID_RERSTREQ,
        CMD_CPRID_RECRDDIAREQ,
        CMD_CPRID_REOBSLOGREQ,
        CMD_CPRID_REOBLOGSTPREQ,
        CMD_CPRID_EXTDATSNDREQ,
        CMD_CPRID_EXTDATRCVRES,
        CMD_CPRID_SLOTINFREQ,
        CMD_CPRID_CARDINFREQ,
        CMD_CPRID_REVERREQ,
        CMD_CPRID_TRXSETREQ,
        CMD_CPRID_TRXRELREQ,
        CMD_CPRID_CARONOFFREQ,
        CMD_CPRID_RECARDCNTREQ,
        CMD_CPRID_REPORTCNTREQ,
        CMD_CPRID_HCRES,
        CMD_CPRID_MTADDSETREQ,
        CMD_CPRID_MTADDSETTOREQ,
        CMD_CPRID_FLDMTCNCRES,
        CMD_CPRID_FLMTCNCRELRES,
        CMD_CPRID_FLMTCMPRELREQ,
        CMD_CPRID_FLDCOMSNDREQ,
        CMD_CPRID_FLDCOMRCVRES,
        CMD_CPRID_FLDFILSNDREQ,
        CMD_CPRID_FLDFILRCVRES,
        CMD_CPRID_SVMTCNTRES,
        CMD_CPRID_SVMTCNTRELRES,
        CMD_CPRID_SVMTFORRELREQ,
        CMD_CPRID_SVMTDATSNDREQ,
        CMD_CPRID_SVMTDATRCVRES,
        CMD_CPRID_FTPPORTSETREQ
};

/* @} */
