###
#
# RU Makefile
#
###

all:	slib

slib:
	cd facc; make slib;
	cd hrtm; make slib;
	cd ipcm; make slib;
	cd itcm; make slib;
	cd mblm; make slib;


clean:
	cd facc; make clean;
	cd hrtm; make clean;
	cd ipcm; make clean;
	cd itcm; make clean;
	cd mblm; make clean;


