#
#   Makefile for OAL
#

all: alllib 
clean: allclean

alllib:
	cd COM;make slib;
	cd RM;make slib;
	cd RU;make slib;

allclean:
	cd COM;make clean;
	cd RM;make clean;
	cd RU;make clean;

