all: alllib 
clean: allclean

alllib:
	#cpr
	cd ./cpr/makefile;make
	#nego
	cd ./nego/makefile;make
	#debug
	cd ./debug;make

allclean:
	#cpr
	cd ./cpr/makefile;make clean
	#nego
	cd ./nego/makefile;make clean
	#debug
	cd ./debug;make clean


